[package]
name = "kronos-worker"
version.workspace = true
edition.workspace = true

[[bin]]
name = "kronos-worker"
path = "src/main.rs"

[features]
default = []
kafka = ["kronos-embedded-worker/kafka"]
redis-stream = ["kronos-embedded-worker/redis-stream"]
kms = ["kronos-embedded-worker/kms", "kronos-common/kms"]

[dependencies]
kronos-common = { path = "../common" }
kronos-embedded-worker = { path = "../embedded-worker" }
tokio.workspace = true
sqlx.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
anyhow.workspace = true
