// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn type_erase_result<O, E>(result: ::std::result::Result<O, E>) -> ::std::result::Result<::aws_smithy_runtime_api::client::interceptors::context::Output, ::aws_smithy_runtime_api::client::orchestrator::OrchestratorError<::aws_smithy_runtime_api::client::interceptors::context::Error>>
                where
                    O: ::std::fmt::Debug + ::std::marker::Send + ::std::marker::Sync + 'static,
                    E: ::std::error::Error + std::fmt::Debug + ::std::marker::Send + ::std::marker::Sync + 'static,
                {
                    result.map(|output| ::aws_smithy_runtime_api::client::interceptors::context::Output::erase(output))
                        .map_err(|error| ::aws_smithy_runtime_api::client::interceptors::context::Error::erase(error))
                        .map_err(::std::convert::Into::into)
                }

pub fn parse_http_error_metadata(_response_status: u16, response_headers: &::aws_smithy_runtime_api::http::Headers, response_body: &[u8]) -> ::std::result::Result<::aws_smithy_types::error::metadata::Builder, ::aws_smithy_json::deserialize::error::DeserializeError> {
                    crate::json_errors::parse_error_metadata(response_body, response_headers)
                }

pub(crate) mod shape_cancel_execution;

pub(crate) mod shape_cancel_job;

pub(crate) mod shape_create_endpoint;

pub(crate) mod shape_create_job;

pub(crate) mod shape_create_payload_spec;

pub(crate) mod shape_delete_endpoint;

pub(crate) mod shape_delete_payload_spec;

pub(crate) mod shape_get_endpoint;

pub(crate) mod shape_get_execution;

pub(crate) mod shape_get_job;

pub(crate) mod shape_get_job_status;

pub(crate) mod shape_get_job_versions;

pub(crate) mod shape_get_payload_spec;

pub(crate) mod shape_list_endpoints;

pub(crate) mod shape_list_execution_attempts;

pub(crate) mod shape_list_execution_logs;

pub(crate) mod shape_list_job_executions;

pub(crate) mod shape_list_jobs;

pub(crate) mod shape_list_payload_specs;

pub(crate) mod shape_update_endpoint;

pub(crate) mod shape_update_job;

pub(crate) mod shape_update_payload_spec;

pub(crate) fn or_empty_doc(data: &[u8]) -> &[u8] {
                    if data.is_empty() {
                        b"{}"
                    } else {
                        data
                    }
                }

pub(crate) mod shape_conflict_error;

pub(crate) mod shape_create_endpoint_input;

pub(crate) mod shape_create_job_input;

pub(crate) mod shape_create_payload_spec_input;

pub(crate) mod shape_internal_error;

pub(crate) mod shape_invalid_request_error;

pub(crate) mod shape_not_found_error;

pub(crate) mod shape_rate_limited_error;

pub(crate) mod shape_unauthorized_error;

pub(crate) mod shape_unprocessable_entity_error;

pub(crate) mod shape_update_endpoint_input;

pub(crate) mod shape_update_job_input;

pub(crate) mod shape_update_payload_spec_input;

pub(crate) mod shape_attempt_resource_list;

pub(crate) mod shape_endpoint_list;

pub(crate) mod shape_endpoint_resource;

pub(crate) mod shape_error_detail;

pub(crate) mod shape_execution_log_list;

pub(crate) mod shape_execution_resource;

pub(crate) mod shape_execution_resource_list;

pub(crate) mod shape_job_resource;

pub(crate) mod shape_job_status_response;

pub(crate) mod shape_job_summary_list;

pub(crate) mod shape_job_version_list;

pub(crate) mod shape_payload_spec_list;

pub(crate) mod shape_payload_spec_resource;

pub(crate) mod shape_retry_policy;

pub(crate) mod shape_attempt_resource;

pub(crate) mod shape_execution_log_resource;

pub(crate) mod shape_execution_summary;

pub(crate) mod shape_job_summary;

