// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetExecutionOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub data: crate::types::ExecutionResource,
}
impl  GetExecutionOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn data(&self) -> &crate::types::ExecutionResource {
        &self.data
    }
}
impl GetExecutionOutput {
    /// Creates a new builder-style object to manufacture [`GetExecutionOutput`](crate::operation::get_execution::GetExecutionOutput).
    pub fn builder() -> crate::operation::get_execution::builders::GetExecutionOutputBuilder {
        crate::operation::get_execution::builders::GetExecutionOutputBuilder::default()
    }
}

/// A builder for [`GetExecutionOutput`](crate::operation::get_execution::GetExecutionOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GetExecutionOutputBuilder {
    pub(crate) data: ::std::option::Option<crate::types::ExecutionResource>,
}
impl GetExecutionOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn data(mut self, input: crate::types::ExecutionResource) -> Self {
        self.data = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_data(mut self, input: ::std::option::Option<crate::types::ExecutionResource>) -> Self {
        self.data = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_data(&self) -> &::std::option::Option<crate::types::ExecutionResource> {
        &self.data
    }
    /// Consumes the builder and constructs a [`GetExecutionOutput`](crate::operation::get_execution::GetExecutionOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`data`](crate::operation::get_execution::builders::GetExecutionOutputBuilder::data)
    pub fn build(self) -> ::std::result::Result<crate::operation::get_execution::GetExecutionOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::get_execution::GetExecutionOutput {
                data: self.data
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("data", "data was not specified but it is required when building GetExecutionOutput")
                    )?
                ,
            }
        )
    }
}

