// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListJobsInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub org_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub workspace_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub cursor: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub limit: ::std::option::Option<i32>,
    /// Exact-match job id filter.
    pub job_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub endpoint: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub trigger_type: ::std::option::Option<::std::vec::Vec::<crate::types::TriggerTypeEnum>>,
    #[allow(missing_docs)] // documentation missing in model
    pub status: ::std::option::Option<::std::vec::Vec::<crate::types::JobStatusEnum>>,
    #[allow(missing_docs)] // documentation missing in model
    pub endpoint_type: ::std::option::Option<::std::vec::Vec::<crate::types::EndpointTypeEnum>>,
    /// Inclusive lower bound on `created_at` (RFC-3339).
    pub created_after: ::std::option::Option<::aws_smithy_types::DateTime>,
    /// Inclusive upper bound on `created_at` (RFC-3339).
    pub created_before: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl  ListJobsInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn org_id(&self) -> ::std::option::Option<&str> {
        self.org_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn workspace_id(&self) -> ::std::option::Option<&str> {
        self.workspace_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cursor(&self) -> ::std::option::Option<&str> {
        self.cursor.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn limit(&self) -> ::std::option::Option<i32> {
        self.limit
    }
    /// Exact-match job id filter.
    pub fn job_id(&self) -> ::std::option::Option<&str> {
        self.job_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint(&self) -> ::std::option::Option<&str> {
        self.endpoint.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    /// 
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.trigger_type.is_none()`.
    pub fn trigger_type(&self) -> &[crate::types::TriggerTypeEnum] {
        self.trigger_type.as_deref()
        .unwrap_or_default()
    }
    #[allow(missing_docs)] // documentation missing in model
    /// 
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.status.is_none()`.
    pub fn status(&self) -> &[crate::types::JobStatusEnum] {
        self.status.as_deref()
        .unwrap_or_default()
    }
    #[allow(missing_docs)] // documentation missing in model
    /// 
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.endpoint_type.is_none()`.
    pub fn endpoint_type(&self) -> &[crate::types::EndpointTypeEnum] {
        self.endpoint_type.as_deref()
        .unwrap_or_default()
    }
    /// Inclusive lower bound on `created_at` (RFC-3339).
    pub fn created_after(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.created_after.as_ref()
    }
    /// Inclusive upper bound on `created_at` (RFC-3339).
    pub fn created_before(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.created_before.as_ref()
    }
}
impl ListJobsInput {
    /// Creates a new builder-style object to manufacture [`ListJobsInput`](crate::operation::list_jobs::ListJobsInput).
    pub fn builder() -> crate::operation::list_jobs::builders::ListJobsInputBuilder {
        crate::operation::list_jobs::builders::ListJobsInputBuilder::default()
    }
}

/// A builder for [`ListJobsInput`](crate::operation::list_jobs::ListJobsInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListJobsInputBuilder {
    pub(crate) org_id: ::std::option::Option<::std::string::String>,
    pub(crate) workspace_id: ::std::option::Option<::std::string::String>,
    pub(crate) cursor: ::std::option::Option<::std::string::String>,
    pub(crate) limit: ::std::option::Option<i32>,
    pub(crate) job_id: ::std::option::Option<::std::string::String>,
    pub(crate) endpoint: ::std::option::Option<::std::string::String>,
    pub(crate) trigger_type: ::std::option::Option<::std::vec::Vec::<crate::types::TriggerTypeEnum>>,
    pub(crate) status: ::std::option::Option<::std::vec::Vec::<crate::types::JobStatusEnum>>,
    pub(crate) endpoint_type: ::std::option::Option<::std::vec::Vec::<crate::types::EndpointTypeEnum>>,
    pub(crate) created_after: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) created_before: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl ListJobsInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn org_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.org_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_org_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.org_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_org_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.org_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn workspace_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.workspace_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_workspace_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.workspace_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_workspace_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.workspace_id
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cursor(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.cursor = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cursor(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.cursor = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cursor(&self) -> &::std::option::Option<::std::string::String> {
        &self.cursor
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn limit(mut self, input: i32) -> Self {
        self.limit = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_limit(mut self, input: ::std::option::Option<i32>) -> Self {
        self.limit = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_limit(&self) -> &::std::option::Option<i32> {
        &self.limit
    }
    /// Exact-match job id filter.
    pub fn job_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.job_id = ::std::option::Option::Some(input.into());
        self
    }
    /// Exact-match job id filter.
    pub fn set_job_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.job_id = input; self
    }
    /// Exact-match job id filter.
    pub fn get_job_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.job_id
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.endpoint = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_endpoint(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.endpoint = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_endpoint(&self) -> &::std::option::Option<::std::string::String> {
        &self.endpoint
    }
    /// Appends an item to `trigger_type`.
    ///
    /// To override the contents of this collection use [`set_trigger_type`](Self::set_trigger_type).
    ///
    pub fn trigger_type(mut self, input: crate::types::TriggerTypeEnum) -> Self {
        let mut v = self.trigger_type.unwrap_or_default();
                        v.push(input);
                        self.trigger_type = ::std::option::Option::Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_trigger_type(mut self, input: ::std::option::Option<::std::vec::Vec::<crate::types::TriggerTypeEnum>>) -> Self {
        self.trigger_type = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_trigger_type(&self) -> &::std::option::Option<::std::vec::Vec::<crate::types::TriggerTypeEnum>> {
        &self.trigger_type
    }
    /// Appends an item to `status`.
    ///
    /// To override the contents of this collection use [`set_status`](Self::set_status).
    ///
    pub fn status(mut self, input: crate::types::JobStatusEnum) -> Self {
        let mut v = self.status.unwrap_or_default();
                        v.push(input);
                        self.status = ::std::option::Option::Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_status(mut self, input: ::std::option::Option<::std::vec::Vec::<crate::types::JobStatusEnum>>) -> Self {
        self.status = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_status(&self) -> &::std::option::Option<::std::vec::Vec::<crate::types::JobStatusEnum>> {
        &self.status
    }
    /// Appends an item to `endpoint_type`.
    ///
    /// To override the contents of this collection use [`set_endpoint_type`](Self::set_endpoint_type).
    ///
    pub fn endpoint_type(mut self, input: crate::types::EndpointTypeEnum) -> Self {
        let mut v = self.endpoint_type.unwrap_or_default();
                        v.push(input);
                        self.endpoint_type = ::std::option::Option::Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_endpoint_type(mut self, input: ::std::option::Option<::std::vec::Vec::<crate::types::EndpointTypeEnum>>) -> Self {
        self.endpoint_type = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_endpoint_type(&self) -> &::std::option::Option<::std::vec::Vec::<crate::types::EndpointTypeEnum>> {
        &self.endpoint_type
    }
    /// Inclusive lower bound on `created_at` (RFC-3339).
    pub fn created_after(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.created_after = ::std::option::Option::Some(input);
        self
    }
    /// Inclusive lower bound on `created_at` (RFC-3339).
    pub fn set_created_after(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.created_after = input; self
    }
    /// Inclusive lower bound on `created_at` (RFC-3339).
    pub fn get_created_after(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.created_after
    }
    /// Inclusive upper bound on `created_at` (RFC-3339).
    pub fn created_before(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.created_before = ::std::option::Option::Some(input);
        self
    }
    /// Inclusive upper bound on `created_at` (RFC-3339).
    pub fn set_created_before(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.created_before = input; self
    }
    /// Inclusive upper bound on `created_at` (RFC-3339).
    pub fn get_created_before(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.created_before
    }
    /// Consumes the builder and constructs a [`ListJobsInput`](crate::operation::list_jobs::ListJobsInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::list_jobs::ListJobsInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::list_jobs::ListJobsInput {
                org_id: self.org_id
                ,
                workspace_id: self.workspace_id
                ,
                cursor: self.cursor
                ,
                limit: self.limit
                ,
                job_id: self.job_id
                ,
                endpoint: self.endpoint
                ,
                trigger_type: self.trigger_type
                ,
                status: self.status
                ,
                endpoint_type: self.endpoint_type
                ,
                created_after: self.created_after
                ,
                created_before: self.created_before
                ,
            }
        )
    }
}

