// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListJobsInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub org_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub workspace_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub cursor: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub limit: ::std::option::Option<i32>,
    #[allow(missing_docs)] // documentation missing in model
    pub endpoint: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub trigger_type: ::std::option::Option<crate::types::TriggerTypeEnum>,
    #[allow(missing_docs)] // documentation missing in model
    pub status: ::std::option::Option<crate::types::JobStatusEnum>,
}
impl  ListJobsInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn org_id(&self) -> ::std::option::Option<&str> {
        self.org_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn workspace_id(&self) -> ::std::option::Option<&str> {
        self.workspace_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cursor(&self) -> ::std::option::Option<&str> {
        self.cursor.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn limit(&self) -> ::std::option::Option<i32> {
        self.limit
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint(&self) -> ::std::option::Option<&str> {
        self.endpoint.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn trigger_type(&self) -> ::std::option::Option<&crate::types::TriggerTypeEnum> {
        self.trigger_type.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(&self) -> ::std::option::Option<&crate::types::JobStatusEnum> {
        self.status.as_ref()
    }
}
impl ListJobsInput {
    /// Creates a new builder-style object to manufacture [`ListJobsInput`](crate::operation::list_jobs::ListJobsInput).
    pub fn builder() -> crate::operation::list_jobs::builders::ListJobsInputBuilder {
        crate::operation::list_jobs::builders::ListJobsInputBuilder::default()
    }
}

/// A builder for [`ListJobsInput`](crate::operation::list_jobs::ListJobsInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListJobsInputBuilder {
    pub(crate) org_id: ::std::option::Option<::std::string::String>,
    pub(crate) workspace_id: ::std::option::Option<::std::string::String>,
    pub(crate) cursor: ::std::option::Option<::std::string::String>,
    pub(crate) limit: ::std::option::Option<i32>,
    pub(crate) endpoint: ::std::option::Option<::std::string::String>,
    pub(crate) trigger_type: ::std::option::Option<crate::types::TriggerTypeEnum>,
    pub(crate) status: ::std::option::Option<crate::types::JobStatusEnum>,
}
impl ListJobsInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn org_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.org_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_org_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.org_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_org_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.org_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn workspace_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.workspace_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_workspace_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.workspace_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_workspace_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.workspace_id
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cursor(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.cursor = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cursor(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.cursor = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cursor(&self) -> &::std::option::Option<::std::string::String> {
        &self.cursor
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn limit(mut self, input: i32) -> Self {
        self.limit = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_limit(mut self, input: ::std::option::Option<i32>) -> Self {
        self.limit = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_limit(&self) -> &::std::option::Option<i32> {
        &self.limit
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.endpoint = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_endpoint(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.endpoint = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_endpoint(&self) -> &::std::option::Option<::std::string::String> {
        &self.endpoint
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn trigger_type(mut self, input: crate::types::TriggerTypeEnum) -> Self {
        self.trigger_type = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_trigger_type(mut self, input: ::std::option::Option<crate::types::TriggerTypeEnum>) -> Self {
        self.trigger_type = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_trigger_type(&self) -> &::std::option::Option<crate::types::TriggerTypeEnum> {
        &self.trigger_type
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(mut self, input: crate::types::JobStatusEnum) -> Self {
        self.status = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::JobStatusEnum>) -> Self {
        self.status = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_status(&self) -> &::std::option::Option<crate::types::JobStatusEnum> {
        &self.status
    }
    /// Consumes the builder and constructs a [`ListJobsInput`](crate::operation::list_jobs::ListJobsInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::list_jobs::ListJobsInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::list_jobs::ListJobsInput {
                org_id: self.org_id
                ,
                workspace_id: self.workspace_id
                ,
                cursor: self.cursor
                ,
                limit: self.limit
                ,
                endpoint: self.endpoint
                ,
                trigger_type: self.trigger_type
                ,
                status: self.status
                ,
            }
        )
    }
}

