-- Migration: Transaction-based job pickup
--
-- SUPERSEDED — intentionally a no-op.
--
-- This migration used to widen the global `idx_executions_pickup` index to
-- cover PENDING, so workers could pick up delayed jobs without a promoter
-- loop. It ran against a public `executions` table.
--
-- `fix: isolate workspaces — drop public data tables (#47)` removed that
-- table: `executions` now only exists inside per-workspace tenant schemas,
-- created from crates/common/migrations/workspace_v1.sql, which already
-- builds the widened index itself:
--
--     CREATE INDEX IF NOT EXISTS idx_{p}executions_pickup
--         ON {p}executions (status, run_at ASC)
--         WHERE status IN ('QUEUED', 'RETRYING', 'PENDING');
--
-- Left in place (rather than deleted) because the filename is referenced by
-- the justfile, scripts/docker-prod.sh, the README and the docs site, and
-- migrations are applied by glob with `ON_ERROR_STOP=1` — the previous
-- contents aborted every fresh-database setup at this file.
