// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetEndpointOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub data: crate::types::EndpointResource,
}
impl  GetEndpointOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn data(&self) -> &crate::types::EndpointResource {
        &self.data
    }
}
impl GetEndpointOutput {
    /// Creates a new builder-style object to manufacture [`GetEndpointOutput`](crate::operation::get_endpoint::GetEndpointOutput).
    pub fn builder() -> crate::operation::get_endpoint::builders::GetEndpointOutputBuilder {
        crate::operation::get_endpoint::builders::GetEndpointOutputBuilder::default()
    }
}

/// A builder for [`GetEndpointOutput`](crate::operation::get_endpoint::GetEndpointOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GetEndpointOutputBuilder {
    pub(crate) data: ::std::option::Option<crate::types::EndpointResource>,
}
impl GetEndpointOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn data(mut self, input: crate::types::EndpointResource) -> Self {
        self.data = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_data(mut self, input: ::std::option::Option<crate::types::EndpointResource>) -> Self {
        self.data = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_data(&self) -> &::std::option::Option<crate::types::EndpointResource> {
        &self.data
    }
    /// Consumes the builder and constructs a [`GetEndpointOutput`](crate::operation::get_endpoint::GetEndpointOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`data`](crate::operation::get_endpoint::builders::GetEndpointOutputBuilder::data)
    pub fn build(self) -> ::std::result::Result<crate::operation::get_endpoint::GetEndpointOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::get_endpoint::GetEndpointOutput {
                data: self.data
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("data", "data was not specified but it is required when building GetEndpointOutput")
                    )?
                ,
            }
        )
    }
}

