// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct UnprocessableEntityError  {
    #[allow(missing_docs)] // documentation missing in model
    pub error: crate::types::ErrorDetail,
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
    pub(crate) meta: ::aws_smithy_types::error::ErrorMetadata,
}
impl  UnprocessableEntityError  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn error(&self) -> &crate::types::ErrorDetail {
        &self.error
    }
}
impl UnprocessableEntityError {
    /// Returns the error message.
                        pub fn message(&self) -> ::std::option::Option<&str> { self.message.as_deref() }
}
impl ::std::fmt::Display for UnprocessableEntityError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "UnprocessableEntityError")?;
        if let ::std::option::Option::Some(inner_1) = &self.message {
             {
                ::std::write!(f, ": {}", inner_1)?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for UnprocessableEntityError {}
impl ::aws_smithy_types::error::metadata::ProvideErrorMetadata for UnprocessableEntityError {
    fn meta(&self) -> &::aws_smithy_types::error::ErrorMetadata { &self.meta }
}
impl UnprocessableEntityError {
    /// Creates a new builder-style object to manufacture [`UnprocessableEntityError`](crate::types::error::UnprocessableEntityError).
    pub fn builder() -> crate::types::error::builders::UnprocessableEntityErrorBuilder {
        crate::types::error::builders::UnprocessableEntityErrorBuilder::default()
    }
}

/// A builder for [`UnprocessableEntityError`](crate::types::error::UnprocessableEntityError).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct UnprocessableEntityErrorBuilder {
    pub(crate) error: ::std::option::Option<crate::types::ErrorDetail>,
    pub(crate) message: ::std::option::Option<::std::string::String>,
    meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>,
}
impl UnprocessableEntityErrorBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn error(mut self, input: crate::types::ErrorDetail) -> Self {
        self.error = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_error(mut self, input: ::std::option::Option<crate::types::ErrorDetail>) -> Self {
        self.error = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_error(&self) -> &::std::option::Option<crate::types::ErrorDetail> {
        &self.error
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    /// Sets error metadata
                                                pub fn meta(mut self, meta: ::aws_smithy_types::error::ErrorMetadata) -> Self {
                                                    self.meta = Some(meta);
                                                    self
                                                }
    
                                                /// Sets error metadata
                                                pub fn set_meta(&mut self, meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>) -> &mut Self {
                                                    self.meta = meta;
                                                    self
                                                }
    /// Consumes the builder and constructs a [`UnprocessableEntityError`](crate::types::error::UnprocessableEntityError).
    /// This method will fail if any of the following fields are not set:
    /// - [`error`](crate::types::error::builders::UnprocessableEntityErrorBuilder::error)
    pub fn build(self) -> ::std::result::Result<crate::types::error::UnprocessableEntityError, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::error::UnprocessableEntityError {
                error: self.error
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("error", "error was not specified but it is required when building UnprocessableEntityError")
                    )?
                ,
                message: self.message
                ,
                meta: self.meta.unwrap_or_default(),
            }
        )
    }
}

