// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CreateEndpointInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub org_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub workspace_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub name: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub endpoint_type: ::std::option::Option<crate::types::EndpointTypeEnum>,
    #[allow(missing_docs)] // documentation missing in model
    pub payload_spec: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub config: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub spec: ::std::option::Option<::aws_smithy_types::Document>,
    #[allow(missing_docs)] // documentation missing in model
    pub retry_policy: ::std::option::Option<crate::types::RetryPolicy>,
}
impl  CreateEndpointInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn org_id(&self) -> ::std::option::Option<&str> {
        self.org_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn workspace_id(&self) -> ::std::option::Option<&str> {
        self.workspace_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn name(&self) -> ::std::option::Option<&str> {
        self.name.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint_type(&self) -> ::std::option::Option<&crate::types::EndpointTypeEnum> {
        self.endpoint_type.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn payload_spec(&self) -> ::std::option::Option<&str> {
        self.payload_spec.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn config(&self) -> ::std::option::Option<&str> {
        self.config.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn spec(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.spec.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn retry_policy(&self) -> ::std::option::Option<&crate::types::RetryPolicy> {
        self.retry_policy.as_ref()
    }
}
impl CreateEndpointInput {
    /// Creates a new builder-style object to manufacture [`CreateEndpointInput`](crate::operation::create_endpoint::CreateEndpointInput).
    pub fn builder() -> crate::operation::create_endpoint::builders::CreateEndpointInputBuilder {
        crate::operation::create_endpoint::builders::CreateEndpointInputBuilder::default()
    }
}

/// A builder for [`CreateEndpointInput`](crate::operation::create_endpoint::CreateEndpointInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CreateEndpointInputBuilder {
    pub(crate) org_id: ::std::option::Option<::std::string::String>,
    pub(crate) workspace_id: ::std::option::Option<::std::string::String>,
    pub(crate) name: ::std::option::Option<::std::string::String>,
    pub(crate) endpoint_type: ::std::option::Option<crate::types::EndpointTypeEnum>,
    pub(crate) payload_spec: ::std::option::Option<::std::string::String>,
    pub(crate) config: ::std::option::Option<::std::string::String>,
    pub(crate) spec: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) retry_policy: ::std::option::Option<crate::types::RetryPolicy>,
}
impl CreateEndpointInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn org_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.org_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_org_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.org_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_org_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.org_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn workspace_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.workspace_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_workspace_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.workspace_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_workspace_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.workspace_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.name = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.name = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.name
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn endpoint_type(mut self, input: crate::types::EndpointTypeEnum) -> Self {
        self.endpoint_type = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_endpoint_type(mut self, input: ::std::option::Option<crate::types::EndpointTypeEnum>) -> Self {
        self.endpoint_type = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_endpoint_type(&self) -> &::std::option::Option<crate::types::EndpointTypeEnum> {
        &self.endpoint_type
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn payload_spec(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.payload_spec = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_payload_spec(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.payload_spec = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_payload_spec(&self) -> &::std::option::Option<::std::string::String> {
        &self.payload_spec
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn config(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.config = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_config(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.config = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_config(&self) -> &::std::option::Option<::std::string::String> {
        &self.config
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn spec(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.spec = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_spec(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.spec = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_spec(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.spec
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn retry_policy(mut self, input: crate::types::RetryPolicy) -> Self {
        self.retry_policy = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_retry_policy(mut self, input: ::std::option::Option<crate::types::RetryPolicy>) -> Self {
        self.retry_policy = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_retry_policy(&self) -> &::std::option::Option<crate::types::RetryPolicy> {
        &self.retry_policy
    }
    /// Consumes the builder and constructs a [`CreateEndpointInput`](crate::operation::create_endpoint::CreateEndpointInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::create_endpoint::CreateEndpointInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::create_endpoint::CreateEndpointInput {
                org_id: self.org_id
                ,
                workspace_id: self.workspace_id
                ,
                name: self.name
                ,
                endpoint_type: self.endpoint_type
                ,
                payload_spec: self.payload_spec
                ,
                config: self.config
                ,
                spec: self.spec
                ,
                retry_policy: self.retry_policy
                ,
            }
        )
    }
}

