// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct AttemptResource  {
    #[allow(missing_docs)] // documentation missing in model
    pub attempt_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub execution_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub attempt_number: i32,
    #[allow(missing_docs)] // documentation missing in model
    pub status: crate::types::AttemptStatusEnum,
    #[allow(missing_docs)] // documentation missing in model
    pub started_at: ::aws_smithy_types::DateTime,
    #[allow(missing_docs)] // documentation missing in model
    pub completed_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub duration_ms: ::std::option::Option<i32>,
    #[allow(missing_docs)] // documentation missing in model
    pub output: ::std::option::Option<::aws_smithy_types::Document>,
    #[allow(missing_docs)] // documentation missing in model
    pub error: ::std::option::Option<::aws_smithy_types::Document>,
    #[allow(missing_docs)] // documentation missing in model
    pub created_at: ::aws_smithy_types::DateTime,
}
impl  AttemptResource  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn attempt_id(&self) -> &str {
        use std::ops::Deref; self.attempt_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn execution_id(&self) -> &str {
        use std::ops::Deref; self.execution_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn attempt_number(&self) -> i32 {
        self.attempt_number
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(&self) -> &crate::types::AttemptStatusEnum {
        &self.status
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn started_at(&self) -> &::aws_smithy_types::DateTime {
        &self.started_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn completed_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.completed_at.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn duration_ms(&self) -> ::std::option::Option<i32> {
        self.duration_ms
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn output(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.output.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn error(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.error.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn created_at(&self) -> &::aws_smithy_types::DateTime {
        &self.created_at
    }
}
impl AttemptResource {
    /// Creates a new builder-style object to manufacture [`AttemptResource`](crate::types::AttemptResource).
    pub fn builder() -> crate::types::builders::AttemptResourceBuilder {
        crate::types::builders::AttemptResourceBuilder::default()
    }
}

/// A builder for [`AttemptResource`](crate::types::AttemptResource).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct AttemptResourceBuilder {
    pub(crate) attempt_id: ::std::option::Option<::std::string::String>,
    pub(crate) execution_id: ::std::option::Option<::std::string::String>,
    pub(crate) attempt_number: ::std::option::Option<i32>,
    pub(crate) status: ::std::option::Option<crate::types::AttemptStatusEnum>,
    pub(crate) started_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) completed_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) duration_ms: ::std::option::Option<i32>,
    pub(crate) output: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) error: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) created_at: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl AttemptResourceBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn attempt_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.attempt_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_attempt_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.attempt_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_attempt_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.attempt_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn execution_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.execution_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_execution_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.execution_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_execution_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.execution_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn attempt_number(mut self, input: i32) -> Self {
        self.attempt_number = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_attempt_number(mut self, input: ::std::option::Option<i32>) -> Self {
        self.attempt_number = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_attempt_number(&self) -> &::std::option::Option<i32> {
        &self.attempt_number
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn status(mut self, input: crate::types::AttemptStatusEnum) -> Self {
        self.status = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::AttemptStatusEnum>) -> Self {
        self.status = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_status(&self) -> &::std::option::Option<crate::types::AttemptStatusEnum> {
        &self.status
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn started_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.started_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_started_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.started_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_started_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.started_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn completed_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.completed_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_completed_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.completed_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_completed_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.completed_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn duration_ms(mut self, input: i32) -> Self {
        self.duration_ms = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_duration_ms(mut self, input: ::std::option::Option<i32>) -> Self {
        self.duration_ms = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_duration_ms(&self) -> &::std::option::Option<i32> {
        &self.duration_ms
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn output(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.output = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_output(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.output = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_output(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.output
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn error(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.error = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_error(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.error = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_error(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.error
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn created_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.created_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_created_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.created_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_created_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.created_at
    }
    /// Consumes the builder and constructs a [`AttemptResource`](crate::types::AttemptResource).
    /// This method will fail if any of the following fields are not set:
    /// - [`attempt_id`](crate::types::builders::AttemptResourceBuilder::attempt_id)
    /// - [`execution_id`](crate::types::builders::AttemptResourceBuilder::execution_id)
    /// - [`attempt_number`](crate::types::builders::AttemptResourceBuilder::attempt_number)
    /// - [`status`](crate::types::builders::AttemptResourceBuilder::status)
    /// - [`started_at`](crate::types::builders::AttemptResourceBuilder::started_at)
    /// - [`created_at`](crate::types::builders::AttemptResourceBuilder::created_at)
    pub fn build(self) -> ::std::result::Result<crate::types::AttemptResource, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::AttemptResource {
                attempt_id: self.attempt_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("attempt_id", "attempt_id was not specified but it is required when building AttemptResource")
                    )?
                ,
                execution_id: self.execution_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("execution_id", "execution_id was not specified but it is required when building AttemptResource")
                    )?
                ,
                attempt_number: self.attempt_number
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("attempt_number", "attempt_number was not specified but it is required when building AttemptResource")
                    )?
                ,
                status: self.status
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("status", "status was not specified but it is required when building AttemptResource")
                    )?
                ,
                started_at: self.started_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("started_at", "started_at was not specified but it is required when building AttemptResource")
                    )?
                ,
                completed_at: self.completed_at
                ,
                duration_ms: self.duration_ms
                ,
                output: self.output
                ,
                error: self.error
                ,
                created_at: self.created_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("created_at", "created_at was not specified but it is required when building AttemptResource")
                    )?
                ,
            }
        )
    }
}

