// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct EndpointResource  {
    #[allow(missing_docs)] // documentation missing in model
    pub name: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub endpoint_type: crate::types::EndpointTypeEnum,
    #[allow(missing_docs)] // documentation missing in model
    pub payload_spec: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub config: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub spec: ::aws_smithy_types::Document,
    #[allow(missing_docs)] // documentation missing in model
    pub retry_policy: ::std::option::Option<crate::types::RetryPolicy>,
    #[allow(missing_docs)] // documentation missing in model
    pub created_at: ::aws_smithy_types::DateTime,
    #[allow(missing_docs)] // documentation missing in model
    pub updated_at: ::aws_smithy_types::DateTime,
}
impl  EndpointResource  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn name(&self) -> &str {
        use std::ops::Deref; self.name.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint_type(&self) -> &crate::types::EndpointTypeEnum {
        &self.endpoint_type
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn payload_spec(&self) -> ::std::option::Option<&str> {
        self.payload_spec.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn config(&self) -> ::std::option::Option<&str> {
        self.config.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn spec(&self) -> &::aws_smithy_types::Document {
        &self.spec
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn retry_policy(&self) -> ::std::option::Option<&crate::types::RetryPolicy> {
        self.retry_policy.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn created_at(&self) -> &::aws_smithy_types::DateTime {
        &self.created_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn updated_at(&self) -> &::aws_smithy_types::DateTime {
        &self.updated_at
    }
}
impl EndpointResource {
    /// Creates a new builder-style object to manufacture [`EndpointResource`](crate::types::EndpointResource).
    pub fn builder() -> crate::types::builders::EndpointResourceBuilder {
        crate::types::builders::EndpointResourceBuilder::default()
    }
}

/// A builder for [`EndpointResource`](crate::types::EndpointResource).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct EndpointResourceBuilder {
    pub(crate) name: ::std::option::Option<::std::string::String>,
    pub(crate) endpoint_type: ::std::option::Option<crate::types::EndpointTypeEnum>,
    pub(crate) payload_spec: ::std::option::Option<::std::string::String>,
    pub(crate) config: ::std::option::Option<::std::string::String>,
    pub(crate) spec: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) retry_policy: ::std::option::Option<crate::types::RetryPolicy>,
    pub(crate) created_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) updated_at: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl EndpointResourceBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.name = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.name = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.name
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn endpoint_type(mut self, input: crate::types::EndpointTypeEnum) -> Self {
        self.endpoint_type = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_endpoint_type(mut self, input: ::std::option::Option<crate::types::EndpointTypeEnum>) -> Self {
        self.endpoint_type = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_endpoint_type(&self) -> &::std::option::Option<crate::types::EndpointTypeEnum> {
        &self.endpoint_type
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn payload_spec(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.payload_spec = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_payload_spec(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.payload_spec = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_payload_spec(&self) -> &::std::option::Option<::std::string::String> {
        &self.payload_spec
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn config(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.config = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_config(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.config = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_config(&self) -> &::std::option::Option<::std::string::String> {
        &self.config
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn spec(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.spec = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_spec(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.spec = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_spec(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.spec
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn retry_policy(mut self, input: crate::types::RetryPolicy) -> Self {
        self.retry_policy = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_retry_policy(mut self, input: ::std::option::Option<crate::types::RetryPolicy>) -> Self {
        self.retry_policy = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_retry_policy(&self) -> &::std::option::Option<crate::types::RetryPolicy> {
        &self.retry_policy
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn created_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.created_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_created_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.created_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_created_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.created_at
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn updated_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.updated_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_updated_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.updated_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_updated_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.updated_at
    }
    /// Consumes the builder and constructs a [`EndpointResource`](crate::types::EndpointResource).
    /// This method will fail if any of the following fields are not set:
    /// - [`name`](crate::types::builders::EndpointResourceBuilder::name)
    /// - [`endpoint_type`](crate::types::builders::EndpointResourceBuilder::endpoint_type)
    /// - [`spec`](crate::types::builders::EndpointResourceBuilder::spec)
    /// - [`created_at`](crate::types::builders::EndpointResourceBuilder::created_at)
    /// - [`updated_at`](crate::types::builders::EndpointResourceBuilder::updated_at)
    pub fn build(self) -> ::std::result::Result<crate::types::EndpointResource, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::EndpointResource {
                name: self.name
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("name", "name was not specified but it is required when building EndpointResource")
                    )?
                ,
                endpoint_type: self.endpoint_type
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("endpoint_type", "endpoint_type was not specified but it is required when building EndpointResource")
                    )?
                ,
                payload_spec: self.payload_spec
                ,
                config: self.config
                ,
                spec: self.spec
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("spec", "spec was not specified but it is required when building EndpointResource")
                    )?
                ,
                retry_policy: self.retry_policy
                ,
                created_at: self.created_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("created_at", "created_at was not specified but it is required when building EndpointResource")
                    )?
                ,
                updated_at: self.updated_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("updated_at", "updated_at was not specified but it is required when building EndpointResource")
                    )?
                ,
            }
        )
    }
}

