// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ErrorDetail  {
    #[allow(missing_docs)] // documentation missing in model
    pub code: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub request_id: ::std::option::Option<::std::string::String>,
}
impl  ErrorDetail  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn code(&self) -> &str {
        use std::ops::Deref; self.code.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn message(&self) -> &str {
        use std::ops::Deref; self.message.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn request_id(&self) -> ::std::option::Option<&str> {
        self.request_id.as_deref()
    }
}
impl ErrorDetail {
    /// Creates a new builder-style object to manufacture [`ErrorDetail`](crate::types::ErrorDetail).
    pub fn builder() -> crate::types::builders::ErrorDetailBuilder {
        crate::types::builders::ErrorDetailBuilder::default()
    }
}

/// A builder for [`ErrorDetail`](crate::types::ErrorDetail).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ErrorDetailBuilder {
    pub(crate) code: ::std::option::Option<::std::string::String>,
    pub(crate) message: ::std::option::Option<::std::string::String>,
    pub(crate) request_id: ::std::option::Option<::std::string::String>,
}
impl ErrorDetailBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn code(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.code = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_code(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.code = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_code(&self) -> &::std::option::Option<::std::string::String> {
        &self.code
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn request_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.request_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_request_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.request_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_request_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.request_id
    }
    /// Consumes the builder and constructs a [`ErrorDetail`](crate::types::ErrorDetail).
    /// This method will fail if any of the following fields are not set:
    /// - [`code`](crate::types::builders::ErrorDetailBuilder::code)
    /// - [`message`](crate::types::builders::ErrorDetailBuilder::message)
    pub fn build(self) -> ::std::result::Result<crate::types::ErrorDetail, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::ErrorDetail {
                code: self.code
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("code", "code was not specified but it is required when building ErrorDetail")
                    )?
                ,
                message: self.message
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("message", "message was not specified but it is required when building ErrorDetail")
                    )?
                ,
                request_id: self.request_id
                ,
            }
        )
    }
}

