// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ExecutionResource  {
    #[allow(missing_docs)] // documentation missing in model
    pub execution_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub job_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub endpoint: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub endpoint_type: crate::types::EndpointTypeEnum,
    #[allow(missing_docs)] // documentation missing in model
    pub idempotency_key: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub status: crate::types::ExecutionStatusEnum,
    #[allow(missing_docs)] // documentation missing in model
    pub input: ::std::option::Option<::aws_smithy_types::Document>,
    #[allow(missing_docs)] // documentation missing in model
    pub output: ::std::option::Option<::aws_smithy_types::Document>,
    #[allow(missing_docs)] // documentation missing in model
    pub attempt_count: i32,
    #[allow(missing_docs)] // documentation missing in model
    pub max_attempts: i32,
    #[allow(missing_docs)] // documentation missing in model
    pub worker_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub run_at: ::aws_smithy_types::DateTime,
    #[allow(missing_docs)] // documentation missing in model
    pub started_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub completed_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub duration_ms: ::std::option::Option<i32>,
    #[allow(missing_docs)] // documentation missing in model
    pub created_at: ::aws_smithy_types::DateTime,
}
impl  ExecutionResource  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn execution_id(&self) -> &str {
        use std::ops::Deref; self.execution_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn job_id(&self) -> &str {
        use std::ops::Deref; self.job_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint(&self) -> &str {
        use std::ops::Deref; self.endpoint.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint_type(&self) -> &crate::types::EndpointTypeEnum {
        &self.endpoint_type
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn idempotency_key(&self) -> ::std::option::Option<&str> {
        self.idempotency_key.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(&self) -> &crate::types::ExecutionStatusEnum {
        &self.status
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn input(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.input.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn output(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.output.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn attempt_count(&self) -> i32 {
        self.attempt_count
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn max_attempts(&self) -> i32 {
        self.max_attempts
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn worker_id(&self) -> ::std::option::Option<&str> {
        self.worker_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn run_at(&self) -> &::aws_smithy_types::DateTime {
        &self.run_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn started_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.started_at.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn completed_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.completed_at.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn duration_ms(&self) -> ::std::option::Option<i32> {
        self.duration_ms
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn created_at(&self) -> &::aws_smithy_types::DateTime {
        &self.created_at
    }
}
impl ExecutionResource {
    /// Creates a new builder-style object to manufacture [`ExecutionResource`](crate::types::ExecutionResource).
    pub fn builder() -> crate::types::builders::ExecutionResourceBuilder {
        crate::types::builders::ExecutionResourceBuilder::default()
    }
}

/// A builder for [`ExecutionResource`](crate::types::ExecutionResource).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ExecutionResourceBuilder {
    pub(crate) execution_id: ::std::option::Option<::std::string::String>,
    pub(crate) job_id: ::std::option::Option<::std::string::String>,
    pub(crate) endpoint: ::std::option::Option<::std::string::String>,
    pub(crate) endpoint_type: ::std::option::Option<crate::types::EndpointTypeEnum>,
    pub(crate) idempotency_key: ::std::option::Option<::std::string::String>,
    pub(crate) status: ::std::option::Option<crate::types::ExecutionStatusEnum>,
    pub(crate) input: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) output: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) attempt_count: ::std::option::Option<i32>,
    pub(crate) max_attempts: ::std::option::Option<i32>,
    pub(crate) worker_id: ::std::option::Option<::std::string::String>,
    pub(crate) run_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) started_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) completed_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) duration_ms: ::std::option::Option<i32>,
    pub(crate) created_at: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl ExecutionResourceBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn execution_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.execution_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_execution_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.execution_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_execution_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.execution_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn job_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.job_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_job_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.job_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_job_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.job_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn endpoint(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.endpoint = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_endpoint(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.endpoint = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_endpoint(&self) -> &::std::option::Option<::std::string::String> {
        &self.endpoint
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn endpoint_type(mut self, input: crate::types::EndpointTypeEnum) -> Self {
        self.endpoint_type = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_endpoint_type(mut self, input: ::std::option::Option<crate::types::EndpointTypeEnum>) -> Self {
        self.endpoint_type = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_endpoint_type(&self) -> &::std::option::Option<crate::types::EndpointTypeEnum> {
        &self.endpoint_type
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn idempotency_key(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.idempotency_key = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_idempotency_key(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.idempotency_key = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_idempotency_key(&self) -> &::std::option::Option<::std::string::String> {
        &self.idempotency_key
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn status(mut self, input: crate::types::ExecutionStatusEnum) -> Self {
        self.status = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::ExecutionStatusEnum>) -> Self {
        self.status = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_status(&self) -> &::std::option::Option<crate::types::ExecutionStatusEnum> {
        &self.status
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn input(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.input = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_input(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.input = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_input(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.input
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn output(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.output = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_output(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.output = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_output(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.output
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn attempt_count(mut self, input: i32) -> Self {
        self.attempt_count = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_attempt_count(mut self, input: ::std::option::Option<i32>) -> Self {
        self.attempt_count = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_attempt_count(&self) -> &::std::option::Option<i32> {
        &self.attempt_count
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn max_attempts(mut self, input: i32) -> Self {
        self.max_attempts = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_max_attempts(mut self, input: ::std::option::Option<i32>) -> Self {
        self.max_attempts = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_max_attempts(&self) -> &::std::option::Option<i32> {
        &self.max_attempts
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn worker_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.worker_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_worker_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.worker_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_worker_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.worker_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn run_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.run_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_run_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.run_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_run_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.run_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn started_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.started_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_started_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.started_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_started_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.started_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn completed_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.completed_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_completed_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.completed_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_completed_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.completed_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn duration_ms(mut self, input: i32) -> Self {
        self.duration_ms = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_duration_ms(mut self, input: ::std::option::Option<i32>) -> Self {
        self.duration_ms = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_duration_ms(&self) -> &::std::option::Option<i32> {
        &self.duration_ms
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn created_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.created_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_created_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.created_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_created_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.created_at
    }
    /// Consumes the builder and constructs a [`ExecutionResource`](crate::types::ExecutionResource).
    /// This method will fail if any of the following fields are not set:
    /// - [`execution_id`](crate::types::builders::ExecutionResourceBuilder::execution_id)
    /// - [`job_id`](crate::types::builders::ExecutionResourceBuilder::job_id)
    /// - [`endpoint`](crate::types::builders::ExecutionResourceBuilder::endpoint)
    /// - [`endpoint_type`](crate::types::builders::ExecutionResourceBuilder::endpoint_type)
    /// - [`status`](crate::types::builders::ExecutionResourceBuilder::status)
    /// - [`attempt_count`](crate::types::builders::ExecutionResourceBuilder::attempt_count)
    /// - [`max_attempts`](crate::types::builders::ExecutionResourceBuilder::max_attempts)
    /// - [`run_at`](crate::types::builders::ExecutionResourceBuilder::run_at)
    /// - [`created_at`](crate::types::builders::ExecutionResourceBuilder::created_at)
    pub fn build(self) -> ::std::result::Result<crate::types::ExecutionResource, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::ExecutionResource {
                execution_id: self.execution_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("execution_id", "execution_id was not specified but it is required when building ExecutionResource")
                    )?
                ,
                job_id: self.job_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("job_id", "job_id was not specified but it is required when building ExecutionResource")
                    )?
                ,
                endpoint: self.endpoint
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("endpoint", "endpoint was not specified but it is required when building ExecutionResource")
                    )?
                ,
                endpoint_type: self.endpoint_type
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("endpoint_type", "endpoint_type was not specified but it is required when building ExecutionResource")
                    )?
                ,
                idempotency_key: self.idempotency_key
                ,
                status: self.status
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("status", "status was not specified but it is required when building ExecutionResource")
                    )?
                ,
                input: self.input
                ,
                output: self.output
                ,
                attempt_count: self.attempt_count
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("attempt_count", "attempt_count was not specified but it is required when building ExecutionResource")
                    )?
                ,
                max_attempts: self.max_attempts
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("max_attempts", "max_attempts was not specified but it is required when building ExecutionResource")
                    )?
                ,
                worker_id: self.worker_id
                ,
                run_at: self.run_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("run_at", "run_at was not specified but it is required when building ExecutionResource")
                    )?
                ,
                started_at: self.started_at
                ,
                completed_at: self.completed_at
                ,
                duration_ms: self.duration_ms
                ,
                created_at: self.created_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("created_at", "created_at was not specified but it is required when building ExecutionResource")
                    )?
                ,
            }
        )
    }
}

