// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct JobStatusResponse  {
    #[allow(missing_docs)] // documentation missing in model
    pub job_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub job_status: crate::types::JobStatusEnum,
    #[allow(missing_docs)] // documentation missing in model
    pub latest_execution: ::std::option::Option<crate::types::ExecutionSummary>,
}
impl  JobStatusResponse  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn job_id(&self) -> &str {
        use std::ops::Deref; self.job_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn job_status(&self) -> &crate::types::JobStatusEnum {
        &self.job_status
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn latest_execution(&self) -> ::std::option::Option<&crate::types::ExecutionSummary> {
        self.latest_execution.as_ref()
    }
}
impl JobStatusResponse {
    /// Creates a new builder-style object to manufacture [`JobStatusResponse`](crate::types::JobStatusResponse).
    pub fn builder() -> crate::types::builders::JobStatusResponseBuilder {
        crate::types::builders::JobStatusResponseBuilder::default()
    }
}

/// A builder for [`JobStatusResponse`](crate::types::JobStatusResponse).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct JobStatusResponseBuilder {
    pub(crate) job_id: ::std::option::Option<::std::string::String>,
    pub(crate) job_status: ::std::option::Option<crate::types::JobStatusEnum>,
    pub(crate) latest_execution: ::std::option::Option<crate::types::ExecutionSummary>,
}
impl JobStatusResponseBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn job_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.job_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_job_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.job_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_job_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.job_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn job_status(mut self, input: crate::types::JobStatusEnum) -> Self {
        self.job_status = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_job_status(mut self, input: ::std::option::Option<crate::types::JobStatusEnum>) -> Self {
        self.job_status = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_job_status(&self) -> &::std::option::Option<crate::types::JobStatusEnum> {
        &self.job_status
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn latest_execution(mut self, input: crate::types::ExecutionSummary) -> Self {
        self.latest_execution = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_latest_execution(mut self, input: ::std::option::Option<crate::types::ExecutionSummary>) -> Self {
        self.latest_execution = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_latest_execution(&self) -> &::std::option::Option<crate::types::ExecutionSummary> {
        &self.latest_execution
    }
    /// Consumes the builder and constructs a [`JobStatusResponse`](crate::types::JobStatusResponse).
    /// This method will fail if any of the following fields are not set:
    /// - [`job_id`](crate::types::builders::JobStatusResponseBuilder::job_id)
    /// - [`job_status`](crate::types::builders::JobStatusResponseBuilder::job_status)
    pub fn build(self) -> ::std::result::Result<crate::types::JobStatusResponse, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::JobStatusResponse {
                job_id: self.job_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("job_id", "job_id was not specified but it is required when building JobStatusResponse")
                    )?
                ,
                job_status: self.job_status
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("job_status", "job_status was not specified but it is required when building JobStatusResponse")
                    )?
                ,
                latest_execution: self.latest_execution
                ,
            }
        )
    }
}

