// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct UpdatePayloadSpecOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub data: crate::types::PayloadSpecResource,
}
impl  UpdatePayloadSpecOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn data(&self) -> &crate::types::PayloadSpecResource {
        &self.data
    }
}
impl UpdatePayloadSpecOutput {
    /// Creates a new builder-style object to manufacture [`UpdatePayloadSpecOutput`](crate::operation::update_payload_spec::UpdatePayloadSpecOutput).
    pub fn builder() -> crate::operation::update_payload_spec::builders::UpdatePayloadSpecOutputBuilder {
        crate::operation::update_payload_spec::builders::UpdatePayloadSpecOutputBuilder::default()
    }
}

/// A builder for [`UpdatePayloadSpecOutput`](crate::operation::update_payload_spec::UpdatePayloadSpecOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct UpdatePayloadSpecOutputBuilder {
    pub(crate) data: ::std::option::Option<crate::types::PayloadSpecResource>,
}
impl UpdatePayloadSpecOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn data(mut self, input: crate::types::PayloadSpecResource) -> Self {
        self.data = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_data(mut self, input: ::std::option::Option<crate::types::PayloadSpecResource>) -> Self {
        self.data = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_data(&self) -> &::std::option::Option<crate::types::PayloadSpecResource> {
        &self.data
    }
    /// Consumes the builder and constructs a [`UpdatePayloadSpecOutput`](crate::operation::update_payload_spec::UpdatePayloadSpecOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`data`](crate::operation::update_payload_spec::builders::UpdatePayloadSpecOutputBuilder::data)
    pub fn build(self) -> ::std::result::Result<crate::operation::update_payload_spec::UpdatePayloadSpecOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::update_payload_spec::UpdatePayloadSpecOutput {
                data: self.data
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("data", "data was not specified but it is required when building UpdatePayloadSpecOutput")
                    )?
                ,
            }
        )
    }
}

