// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_update_job_input_input(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::operation::update_job::UpdateJobInput,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.cron {
        object.key("cron").string(var_1.as_str());
    }
    if let Some(var_2) = &input.ends_at {
        object.key("ends_at").date_time(var_2, ::aws_smithy_types::date_time::Format::DateTime)?;
    }
    if let Some(var_3) = &input.input {
        object.key("input").document(var_3);
    }
    if let Some(var_4) = &input.starts_at {
        object.key("starts_at").date_time(var_4, ::aws_smithy_types::date_time::Format::DateTime)?;
    }
    if let Some(var_5) = &input.timezone {
        object.key("timezone").string(var_5.as_str());
    }
    Ok(())
}

