// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_create_endpoint_input_input(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::operation::create_endpoint::CreateEndpointInput,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.config {
        object.key("config").string(var_1.as_str());
    }
    if let Some(var_2) = &input.endpoint_type {
        object.key("type").string(var_2.as_str());
    }
    if let Some(var_3) = &input.name {
        object.key("name").string(var_3.as_str());
    }
    if let Some(var_4) = &input.payload_spec {
        object.key("payload_spec").string(var_4.as_str());
    }
    if let Some(var_5) = &input.retry_policy {
        #[allow(unused_mut)]
        let mut object_6 = object.key("retry_policy").start_object();
        crate::protocol_serde::shape_retry_policy::ser_retry_policy(&mut object_6, var_5)?;
        object_6.finish();
    }
    if let Some(var_7) = &input.spec {
        object.key("spec").document(var_7);
    }
    Ok(())
}

