// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_create_job_input_input(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::operation::create_job::CreateJobInput,
                    ) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.cron {
        object.key("cron").string(var_1.as_str());
    }
    if let Some(var_2) = &input.endpoint {
        object.key("endpoint").string(var_2.as_str());
    }
    if let Some(var_3) = &input.ends_at {
        object.key("ends_at").date_time(var_3, ::aws_smithy_types::date_time::Format::DateTime)?;
    }
    if let Some(var_4) = &input.idempotency_key {
        object.key("idempotency_key").string(var_4.as_str());
    }
    if let Some(var_5) = &input.input {
        object.key("input").document(var_5);
    }
    if let Some(var_6) = &input.run_at {
        object.key("run_at").date_time(var_6, ::aws_smithy_types::date_time::Format::DateTime)?;
    }
    if let Some(var_7) = &input.starts_at {
        object.key("starts_at").date_time(var_7, ::aws_smithy_types::date_time::Format::DateTime)?;
    }
    if let Some(var_8) = &input.timezone {
        object.key("timezone").string(var_8.as_str());
    }
    if let Some(var_9) = &input.trigger {
        object.key("trigger").string(var_9.as_str());
    }
    Ok(())
}

