// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub fn de_cancel_job_http_error(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::cancel_job::CancelJobOutput, crate::operation::cancel_job::CancelJobError> {
    #[allow(unused_mut)]
    let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body).map_err(crate::operation::cancel_job::CancelJobError::unhandled)?;
    let generic = generic_builder.build();
    let error_code = match generic.code() {
                                Some(code) => code,
                                None => return Err(crate::operation::cancel_job::CancelJobError::unhandled(generic))
                            };
    
                            let _error_message = generic.message().map(|msg|msg.to_owned());
    Err(match error_code {
        "NotFoundError" => crate::operation::cancel_job::CancelJobError::NotFoundError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::NotFoundErrorBuilder::default();
                    output = crate::protocol_serde::shape_not_found_error::de_not_found_error_json_err(_response_body, output).map_err(crate::operation::cancel_job::CancelJobError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::not_found_error_correct_errors(output).build().map_err(crate::operation::cancel_job::CancelJobError::unhandled)?
                }
            ;
            if tmp.message.is_none() {
                                                            tmp.message = _error_message;
                                                        }
            tmp
        }),
        "ConflictError" => crate::operation::cancel_job::CancelJobError::ConflictError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::ConflictErrorBuilder::default();
                    output = crate::protocol_serde::shape_conflict_error::de_conflict_error_json_err(_response_body, output).map_err(crate::operation::cancel_job::CancelJobError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::conflict_error_correct_errors(output).build().map_err(crate::operation::cancel_job::CancelJobError::unhandled)?
                }
            ;
            if tmp.message.is_none() {
                                                            tmp.message = _error_message;
                                                        }
            tmp
        }),
        "UnauthorizedError" => crate::operation::cancel_job::CancelJobError::UnauthorizedError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::UnauthorizedErrorBuilder::default();
                    output = crate::protocol_serde::shape_unauthorized_error::de_unauthorized_error_json_err(_response_body, output).map_err(crate::operation::cancel_job::CancelJobError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::unauthorized_error_correct_errors(output).build().map_err(crate::operation::cancel_job::CancelJobError::unhandled)?
                }
            ;
            if tmp.message.is_none() {
                                                            tmp.message = _error_message;
                                                        }
            tmp
        }),
        "InternalError" => crate::operation::cancel_job::CancelJobError::InternalError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::InternalErrorBuilder::default();
                    output = crate::protocol_serde::shape_internal_error::de_internal_error_json_err(_response_body, output).map_err(crate::operation::cancel_job::CancelJobError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::internal_error_correct_errors(output).build().map_err(crate::operation::cancel_job::CancelJobError::unhandled)?
                }
            ;
            if tmp.message.is_none() {
                                                            tmp.message = _error_message;
                                                        }
            tmp
        }),
        "RateLimitedError" => crate::operation::cancel_job::CancelJobError::RateLimitedError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::RateLimitedErrorBuilder::default();
                    output = crate::protocol_serde::shape_rate_limited_error::de_rate_limited_error_json_err(_response_body, output).map_err(crate::operation::cancel_job::CancelJobError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::rate_limited_error_correct_errors(output).build().map_err(crate::operation::cancel_job::CancelJobError::unhandled)?
                }
            ;
            if tmp.message.is_none() {
                                                            tmp.message = _error_message;
                                                        }
            tmp
        }),
        _ => crate::operation::cancel_job::CancelJobError::generic(generic)
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn de_cancel_job_http_response(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::cancel_job::CancelJobOutput, crate::operation::cancel_job::CancelJobError> {
    Ok({
        #[allow(unused_mut)]
        let mut output = crate::operation::cancel_job::builders::CancelJobOutputBuilder::default();
        output = crate::protocol_serde::shape_cancel_job::de_cancel_job(_response_body, output).map_err(crate::operation::cancel_job::CancelJobError::unhandled)?;
        crate::serde_util::cancel_job_output_output_correct_errors(output).build().map_err(crate::operation::cancel_job::CancelJobError::unhandled)?
    })
}

pub fn ser_cancel_job_headers(
                    input: &crate::operation::cancel_job::CancelJobInput,
                    mut builder: ::http::request::Builder
                ) -> std::result::Result<::http::request::Builder, ::aws_smithy_types::error::operation::BuildError> {
    if let ::std::option::Option::Some(inner_1) = &input.org_id {
        let formatted_2 = inner_1.as_str();
        let header_value = formatted_2;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("org_id", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-org-id", header_value);
    }
    if let ::std::option::Option::Some(inner_3) = &input.workspace_id {
        let formatted_4 = inner_3.as_str();
        let header_value = formatted_4;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("workspace_id", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-workspace-id", header_value);
    }
    Ok(builder)
}

pub(crate) fn de_cancel_job(value: &[u8], mut builder: crate::operation::cancel_job::builders::CancelJobOutputBuilder) -> ::std::result::Result<crate::operation::cancel_job::builders::CancelJobOutputBuilder, ::aws_smithy_json::deserialize::error::DeserializeError> {
    let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
                        let tokens = &mut tokens_owned;
                        ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    loop {
        match tokens.next().transpose()? {
            Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                                    Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                match key.to_unescaped()?.as_ref() {
                    "data" => {
                        builder = builder.set_data(
                            crate::protocol_serde::shape_job_resource::de_job_resource(tokens)?
                        );
                    }
                    _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
                }
            }
            other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
        }
    }
    if tokens.next().is_some() {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("found more JSON tokens after completing parsing"));
    }
    Ok(builder)
}

