// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn not_found_error_correct_errors(mut builder: crate::types::error::builders::NotFoundErrorBuilder) -> crate::types::error::builders::NotFoundErrorBuilder {
                if builder.error.is_none() { builder.error = { let builder = crate::types::builders::ErrorDetailBuilder::default(); crate::serde_util::error_detail_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn conflict_error_correct_errors(mut builder: crate::types::error::builders::ConflictErrorBuilder) -> crate::types::error::builders::ConflictErrorBuilder {
                if builder.error.is_none() { builder.error = { let builder = crate::types::builders::ErrorDetailBuilder::default(); crate::serde_util::error_detail_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn unauthorized_error_correct_errors(mut builder: crate::types::error::builders::UnauthorizedErrorBuilder) -> crate::types::error::builders::UnauthorizedErrorBuilder {
                if builder.error.is_none() { builder.error = { let builder = crate::types::builders::ErrorDetailBuilder::default(); crate::serde_util::error_detail_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn internal_error_correct_errors(mut builder: crate::types::error::builders::InternalErrorBuilder) -> crate::types::error::builders::InternalErrorBuilder {
                if builder.error.is_none() { builder.error = { let builder = crate::types::builders::ErrorDetailBuilder::default(); crate::serde_util::error_detail_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn rate_limited_error_correct_errors(mut builder: crate::types::error::builders::RateLimitedErrorBuilder) -> crate::types::error::builders::RateLimitedErrorBuilder {
                if builder.error.is_none() { builder.error = { let builder = crate::types::builders::ErrorDetailBuilder::default(); crate::serde_util::error_detail_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn cancel_execution_output_output_correct_errors(mut builder: crate::operation::cancel_execution::builders::CancelExecutionOutputBuilder) -> crate::operation::cancel_execution::builders::CancelExecutionOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::ExecutionResourceBuilder::default(); crate::serde_util::execution_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn cancel_job_output_output_correct_errors(mut builder: crate::operation::cancel_job::builders::CancelJobOutputBuilder) -> crate::operation::cancel_job::builders::CancelJobOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::JobResourceBuilder::default(); crate::serde_util::job_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn invalid_request_error_correct_errors(mut builder: crate::types::error::builders::InvalidRequestErrorBuilder) -> crate::types::error::builders::InvalidRequestErrorBuilder {
                if builder.error.is_none() { builder.error = { let builder = crate::types::builders::ErrorDetailBuilder::default(); crate::serde_util::error_detail_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn unprocessable_entity_error_correct_errors(mut builder: crate::types::error::builders::UnprocessableEntityErrorBuilder) -> crate::types::error::builders::UnprocessableEntityErrorBuilder {
                if builder.error.is_none() { builder.error = { let builder = crate::types::builders::ErrorDetailBuilder::default(); crate::serde_util::error_detail_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn create_endpoint_output_output_correct_errors(mut builder: crate::operation::create_endpoint::builders::CreateEndpointOutputBuilder) -> crate::operation::create_endpoint::builders::CreateEndpointOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::EndpointResourceBuilder::default(); crate::serde_util::endpoint_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn create_job_output_output_correct_errors(mut builder: crate::operation::create_job::builders::CreateJobOutputBuilder) -> crate::operation::create_job::builders::CreateJobOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::JobResourceBuilder::default(); crate::serde_util::job_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn create_payload_spec_output_output_correct_errors(mut builder: crate::operation::create_payload_spec::builders::CreatePayloadSpecOutputBuilder) -> crate::operation::create_payload_spec::builders::CreatePayloadSpecOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::PayloadSpecResourceBuilder::default(); crate::serde_util::payload_spec_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn get_endpoint_output_output_correct_errors(mut builder: crate::operation::get_endpoint::builders::GetEndpointOutputBuilder) -> crate::operation::get_endpoint::builders::GetEndpointOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::EndpointResourceBuilder::default(); crate::serde_util::endpoint_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn get_execution_output_output_correct_errors(mut builder: crate::operation::get_execution::builders::GetExecutionOutputBuilder) -> crate::operation::get_execution::builders::GetExecutionOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::ExecutionResourceBuilder::default(); crate::serde_util::execution_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn get_job_output_output_correct_errors(mut builder: crate::operation::get_job::builders::GetJobOutputBuilder) -> crate::operation::get_job::builders::GetJobOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::JobResourceBuilder::default(); crate::serde_util::job_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn get_job_status_output_output_correct_errors(mut builder: crate::operation::get_job_status::builders::GetJobStatusOutputBuilder) -> crate::operation::get_job_status::builders::GetJobStatusOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::JobStatusResponseBuilder::default(); crate::serde_util::job_status_response_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn get_job_versions_output_output_correct_errors(mut builder: crate::operation::get_job_versions::builders::GetJobVersionsOutputBuilder) -> crate::operation::get_job_versions::builders::GetJobVersionsOutputBuilder {
                if builder.data.is_none() { builder.data = Some(Default::default()) }
                builder
            }

pub(crate) fn get_payload_spec_output_output_correct_errors(mut builder: crate::operation::get_payload_spec::builders::GetPayloadSpecOutputBuilder) -> crate::operation::get_payload_spec::builders::GetPayloadSpecOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::PayloadSpecResourceBuilder::default(); crate::serde_util::payload_spec_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn list_endpoints_output_output_correct_errors(mut builder: crate::operation::list_endpoints::builders::ListEndpointsOutputBuilder) -> crate::operation::list_endpoints::builders::ListEndpointsOutputBuilder {
                if builder.data.is_none() { builder.data = Some(Default::default()) }
                builder
            }

pub(crate) fn list_execution_attempts_output_output_correct_errors(mut builder: crate::operation::list_execution_attempts::builders::ListExecutionAttemptsOutputBuilder) -> crate::operation::list_execution_attempts::builders::ListExecutionAttemptsOutputBuilder {
                if builder.data.is_none() { builder.data = Some(Default::default()) }
                builder
            }

pub(crate) fn list_execution_logs_output_output_correct_errors(mut builder: crate::operation::list_execution_logs::builders::ListExecutionLogsOutputBuilder) -> crate::operation::list_execution_logs::builders::ListExecutionLogsOutputBuilder {
                if builder.data.is_none() { builder.data = Some(Default::default()) }
                builder
            }

pub(crate) fn list_job_executions_output_output_correct_errors(mut builder: crate::operation::list_job_executions::builders::ListJobExecutionsOutputBuilder) -> crate::operation::list_job_executions::builders::ListJobExecutionsOutputBuilder {
                if builder.data.is_none() { builder.data = Some(Default::default()) }
                builder
            }

pub(crate) fn list_jobs_output_output_correct_errors(mut builder: crate::operation::list_jobs::builders::ListJobsOutputBuilder) -> crate::operation::list_jobs::builders::ListJobsOutputBuilder {
                if builder.data.is_none() { builder.data = Some(Default::default()) }
                builder
            }

pub(crate) fn list_payload_specs_output_output_correct_errors(mut builder: crate::operation::list_payload_specs::builders::ListPayloadSpecsOutputBuilder) -> crate::operation::list_payload_specs::builders::ListPayloadSpecsOutputBuilder {
                if builder.data.is_none() { builder.data = Some(Default::default()) }
                builder
            }

pub(crate) fn update_endpoint_output_output_correct_errors(mut builder: crate::operation::update_endpoint::builders::UpdateEndpointOutputBuilder) -> crate::operation::update_endpoint::builders::UpdateEndpointOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::EndpointResourceBuilder::default(); crate::serde_util::endpoint_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn update_job_output_output_correct_errors(mut builder: crate::operation::update_job::builders::UpdateJobOutputBuilder) -> crate::operation::update_job::builders::UpdateJobOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::JobResourceBuilder::default(); crate::serde_util::job_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn update_payload_spec_output_output_correct_errors(mut builder: crate::operation::update_payload_spec::builders::UpdatePayloadSpecOutputBuilder) -> crate::operation::update_payload_spec::builders::UpdatePayloadSpecOutputBuilder {
                if builder.data.is_none() { builder.data = { let builder = crate::types::builders::PayloadSpecResourceBuilder::default(); crate::serde_util::payload_spec_resource_correct_errors(builder).build().ok() } }
                builder
            }

pub(crate) fn error_detail_correct_errors(mut builder: crate::types::builders::ErrorDetailBuilder) -> crate::types::builders::ErrorDetailBuilder {
                if builder.code.is_none() { builder.code = Some(Default::default()) }
if builder.message.is_none() { builder.message = Some(Default::default()) }
                builder
            }

pub(crate) fn execution_resource_correct_errors(mut builder: crate::types::builders::ExecutionResourceBuilder) -> crate::types::builders::ExecutionResourceBuilder {
                if builder.execution_id.is_none() { builder.execution_id = Some(Default::default()) }
if builder.job_id.is_none() { builder.job_id = Some(Default::default()) }
if builder.endpoint.is_none() { builder.endpoint = Some(Default::default()) }
if builder.endpoint_type.is_none() { builder.endpoint_type = "no value was set".parse::<crate::types::EndpointTypeEnum>().ok() }
if builder.status.is_none() { builder.status = "no value was set".parse::<crate::types::ExecutionStatusEnum>().ok() }
if builder.attempt_count.is_none() { builder.attempt_count = Some(Default::default()) }
if builder.max_attempts.is_none() { builder.max_attempts = Some(Default::default()) }
if builder.run_at.is_none() { builder.run_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
if builder.created_at.is_none() { builder.created_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
                builder
            }

pub(crate) fn job_resource_correct_errors(mut builder: crate::types::builders::JobResourceBuilder) -> crate::types::builders::JobResourceBuilder {
                if builder.job_id.is_none() { builder.job_id = Some(Default::default()) }
if builder.endpoint.is_none() { builder.endpoint = Some(Default::default()) }
if builder.endpoint_type.is_none() { builder.endpoint_type = "no value was set".parse::<crate::types::EndpointTypeEnum>().ok() }
if builder.trigger_type.is_none() { builder.trigger_type = "no value was set".parse::<crate::types::TriggerTypeEnum>().ok() }
if builder.status.is_none() { builder.status = "no value was set".parse::<crate::types::JobStatusEnum>().ok() }
if builder.version.is_none() { builder.version = Some(Default::default()) }
if builder.created_at.is_none() { builder.created_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
                builder
            }

pub(crate) fn endpoint_resource_correct_errors(mut builder: crate::types::builders::EndpointResourceBuilder) -> crate::types::builders::EndpointResourceBuilder {
                if builder.name.is_none() { builder.name = Some(Default::default()) }
if builder.endpoint_type.is_none() { builder.endpoint_type = "no value was set".parse::<crate::types::EndpointTypeEnum>().ok() }
if builder.spec.is_none() { builder.spec = Some(Default::default()) }
if builder.created_at.is_none() { builder.created_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
if builder.updated_at.is_none() { builder.updated_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
                builder
            }

pub(crate) fn payload_spec_resource_correct_errors(mut builder: crate::types::builders::PayloadSpecResourceBuilder) -> crate::types::builders::PayloadSpecResourceBuilder {
                if builder.name.is_none() { builder.name = Some(Default::default()) }
if builder.schema.is_none() { builder.schema = Some(Default::default()) }
if builder.created_at.is_none() { builder.created_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
if builder.updated_at.is_none() { builder.updated_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
                builder
            }

pub(crate) fn job_status_response_correct_errors(mut builder: crate::types::builders::JobStatusResponseBuilder) -> crate::types::builders::JobStatusResponseBuilder {
                if builder.job_id.is_none() { builder.job_id = Some(Default::default()) }
if builder.job_status.is_none() { builder.job_status = "no value was set".parse::<crate::types::JobStatusEnum>().ok() }
                builder
            }

pub(crate) fn attempt_resource_correct_errors(mut builder: crate::types::builders::AttemptResourceBuilder) -> crate::types::builders::AttemptResourceBuilder {
                if builder.attempt_id.is_none() { builder.attempt_id = Some(Default::default()) }
if builder.execution_id.is_none() { builder.execution_id = Some(Default::default()) }
if builder.attempt_number.is_none() { builder.attempt_number = Some(Default::default()) }
if builder.status.is_none() { builder.status = "no value was set".parse::<crate::types::AttemptStatusEnum>().ok() }
if builder.started_at.is_none() { builder.started_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
if builder.created_at.is_none() { builder.created_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
                builder
            }

pub(crate) fn execution_log_resource_correct_errors(mut builder: crate::types::builders::ExecutionLogResourceBuilder) -> crate::types::builders::ExecutionLogResourceBuilder {
                if builder.log_id.is_none() { builder.log_id = Some(Default::default()) }
if builder.execution_id.is_none() { builder.execution_id = Some(Default::default()) }
if builder.attempt_number.is_none() { builder.attempt_number = Some(Default::default()) }
if builder.level.is_none() { builder.level = "no value was set".parse::<crate::types::LogLevelEnum>().ok() }
if builder.message.is_none() { builder.message = Some(Default::default()) }
if builder.logged_at.is_none() { builder.logged_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
                builder
            }

pub(crate) fn execution_summary_correct_errors(mut builder: crate::types::builders::ExecutionSummaryBuilder) -> crate::types::builders::ExecutionSummaryBuilder {
                if builder.execution_id.is_none() { builder.execution_id = Some(Default::default()) }
if builder.status.is_none() { builder.status = "no value was set".parse::<crate::types::ExecutionStatusEnum>().ok() }
if builder.attempt_count.is_none() { builder.attempt_count = Some(Default::default()) }
if builder.max_attempts.is_none() { builder.max_attempts = Some(Default::default()) }
                builder
            }

pub(crate) fn job_summary_correct_errors(mut builder: crate::types::builders::JobSummaryBuilder) -> crate::types::builders::JobSummaryBuilder {
                if builder.job_id.is_none() { builder.job_id = Some(Default::default()) }
if builder.endpoint.is_none() { builder.endpoint = Some(Default::default()) }
if builder.trigger_type.is_none() { builder.trigger_type = "no value was set".parse::<crate::types::TriggerTypeEnum>().ok() }
if builder.status.is_none() { builder.status = "no value was set".parse::<crate::types::JobStatusEnum>().ok() }
if builder.version.is_none() { builder.version = Some(Default::default()) }
if builder.created_at.is_none() { builder.created_at = Some(::aws_smithy_types::DateTime::from_fractional_secs(0, 0_f64)) }
                builder
            }

