apiVersion: v1
kind: Service
metadata:
  name: {{ include "invokr.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "invokr.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "invokr.componentSelectorLabels" (dict "root" . "component" "api") | nindent 4 }}
