// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct JobResource  {
    #[allow(missing_docs)] // documentation missing in model
    pub job_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub endpoint: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub endpoint_type: crate::types::EndpointTypeEnum,
    #[allow(missing_docs)] // documentation missing in model
    pub trigger_type: crate::types::TriggerTypeEnum,
    #[allow(missing_docs)] // documentation missing in model
    pub status: crate::types::JobStatusEnum,
    #[allow(missing_docs)] // documentation missing in model
    pub version: i32,
    #[allow(missing_docs)] // documentation missing in model
    pub previous_version_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub replaced_by_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub idempotency_key: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub input: ::std::option::Option<::aws_smithy_types::Document>,
    #[allow(missing_docs)] // documentation missing in model
    pub run_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub cron_expression: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub cron_timezone: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub cron_starts_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub cron_ends_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub cron_next_run_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub cron_last_tick_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub created_at: ::aws_smithy_types::DateTime,
    #[allow(missing_docs)] // documentation missing in model
    pub retired_at: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl  JobResource  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn job_id(&self) -> &str {
        use std::ops::Deref; self.job_id.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint(&self) -> &str {
        use std::ops::Deref; self.endpoint.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint_type(&self) -> &crate::types::EndpointTypeEnum {
        &self.endpoint_type
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn trigger_type(&self) -> &crate::types::TriggerTypeEnum {
        &self.trigger_type
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(&self) -> &crate::types::JobStatusEnum {
        &self.status
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn version(&self) -> i32 {
        self.version
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn previous_version_id(&self) -> ::std::option::Option<&str> {
        self.previous_version_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn replaced_by_id(&self) -> ::std::option::Option<&str> {
        self.replaced_by_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn idempotency_key(&self) -> ::std::option::Option<&str> {
        self.idempotency_key.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn input(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.input.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn run_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.run_at.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_expression(&self) -> ::std::option::Option<&str> {
        self.cron_expression.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_timezone(&self) -> ::std::option::Option<&str> {
        self.cron_timezone.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_starts_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.cron_starts_at.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_ends_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.cron_ends_at.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_next_run_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.cron_next_run_at.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_last_tick_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.cron_last_tick_at.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn created_at(&self) -> &::aws_smithy_types::DateTime {
        &self.created_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn retired_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.retired_at.as_ref()
    }
}
impl JobResource {
    /// Creates a new builder-style object to manufacture [`JobResource`](crate::types::JobResource).
    pub fn builder() -> crate::types::builders::JobResourceBuilder {
        crate::types::builders::JobResourceBuilder::default()
    }
}

/// A builder for [`JobResource`](crate::types::JobResource).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct JobResourceBuilder {
    pub(crate) job_id: ::std::option::Option<::std::string::String>,
    pub(crate) endpoint: ::std::option::Option<::std::string::String>,
    pub(crate) endpoint_type: ::std::option::Option<crate::types::EndpointTypeEnum>,
    pub(crate) trigger_type: ::std::option::Option<crate::types::TriggerTypeEnum>,
    pub(crate) status: ::std::option::Option<crate::types::JobStatusEnum>,
    pub(crate) version: ::std::option::Option<i32>,
    pub(crate) previous_version_id: ::std::option::Option<::std::string::String>,
    pub(crate) replaced_by_id: ::std::option::Option<::std::string::String>,
    pub(crate) idempotency_key: ::std::option::Option<::std::string::String>,
    pub(crate) input: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) run_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) cron_expression: ::std::option::Option<::std::string::String>,
    pub(crate) cron_timezone: ::std::option::Option<::std::string::String>,
    pub(crate) cron_starts_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) cron_ends_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) cron_next_run_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) cron_last_tick_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) created_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) retired_at: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl JobResourceBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn job_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.job_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_job_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.job_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_job_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.job_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn endpoint(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.endpoint = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_endpoint(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.endpoint = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_endpoint(&self) -> &::std::option::Option<::std::string::String> {
        &self.endpoint
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn endpoint_type(mut self, input: crate::types::EndpointTypeEnum) -> Self {
        self.endpoint_type = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_endpoint_type(mut self, input: ::std::option::Option<crate::types::EndpointTypeEnum>) -> Self {
        self.endpoint_type = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_endpoint_type(&self) -> &::std::option::Option<crate::types::EndpointTypeEnum> {
        &self.endpoint_type
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn trigger_type(mut self, input: crate::types::TriggerTypeEnum) -> Self {
        self.trigger_type = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_trigger_type(mut self, input: ::std::option::Option<crate::types::TriggerTypeEnum>) -> Self {
        self.trigger_type = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_trigger_type(&self) -> &::std::option::Option<crate::types::TriggerTypeEnum> {
        &self.trigger_type
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn status(mut self, input: crate::types::JobStatusEnum) -> Self {
        self.status = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::JobStatusEnum>) -> Self {
        self.status = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_status(&self) -> &::std::option::Option<crate::types::JobStatusEnum> {
        &self.status
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn version(mut self, input: i32) -> Self {
        self.version = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_version(mut self, input: ::std::option::Option<i32>) -> Self {
        self.version = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_version(&self) -> &::std::option::Option<i32> {
        &self.version
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn previous_version_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.previous_version_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_previous_version_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.previous_version_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_previous_version_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.previous_version_id
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn replaced_by_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.replaced_by_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_replaced_by_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.replaced_by_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_replaced_by_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.replaced_by_id
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn idempotency_key(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.idempotency_key = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_idempotency_key(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.idempotency_key = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_idempotency_key(&self) -> &::std::option::Option<::std::string::String> {
        &self.idempotency_key
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn input(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.input = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_input(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.input = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_input(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.input
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn run_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.run_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_run_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.run_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_run_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.run_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_expression(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.cron_expression = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cron_expression(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.cron_expression = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cron_expression(&self) -> &::std::option::Option<::std::string::String> {
        &self.cron_expression
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_timezone(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.cron_timezone = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cron_timezone(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.cron_timezone = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cron_timezone(&self) -> &::std::option::Option<::std::string::String> {
        &self.cron_timezone
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_starts_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.cron_starts_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cron_starts_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.cron_starts_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cron_starts_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.cron_starts_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_ends_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.cron_ends_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cron_ends_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.cron_ends_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cron_ends_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.cron_ends_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_next_run_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.cron_next_run_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cron_next_run_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.cron_next_run_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cron_next_run_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.cron_next_run_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron_last_tick_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.cron_last_tick_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cron_last_tick_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.cron_last_tick_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cron_last_tick_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.cron_last_tick_at
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn created_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.created_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_created_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.created_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_created_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.created_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn retired_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.retired_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_retired_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.retired_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_retired_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.retired_at
    }
    /// Consumes the builder and constructs a [`JobResource`](crate::types::JobResource).
    /// This method will fail if any of the following fields are not set:
    /// - [`job_id`](crate::types::builders::JobResourceBuilder::job_id)
    /// - [`endpoint`](crate::types::builders::JobResourceBuilder::endpoint)
    /// - [`endpoint_type`](crate::types::builders::JobResourceBuilder::endpoint_type)
    /// - [`trigger_type`](crate::types::builders::JobResourceBuilder::trigger_type)
    /// - [`status`](crate::types::builders::JobResourceBuilder::status)
    /// - [`version`](crate::types::builders::JobResourceBuilder::version)
    /// - [`created_at`](crate::types::builders::JobResourceBuilder::created_at)
    pub fn build(self) -> ::std::result::Result<crate::types::JobResource, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::JobResource {
                job_id: self.job_id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("job_id", "job_id was not specified but it is required when building JobResource")
                    )?
                ,
                endpoint: self.endpoint
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("endpoint", "endpoint was not specified but it is required when building JobResource")
                    )?
                ,
                endpoint_type: self.endpoint_type
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("endpoint_type", "endpoint_type was not specified but it is required when building JobResource")
                    )?
                ,
                trigger_type: self.trigger_type
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("trigger_type", "trigger_type was not specified but it is required when building JobResource")
                    )?
                ,
                status: self.status
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("status", "status was not specified but it is required when building JobResource")
                    )?
                ,
                version: self.version
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("version", "version was not specified but it is required when building JobResource")
                    )?
                ,
                previous_version_id: self.previous_version_id
                ,
                replaced_by_id: self.replaced_by_id
                ,
                idempotency_key: self.idempotency_key
                ,
                input: self.input
                ,
                run_at: self.run_at
                ,
                cron_expression: self.cron_expression
                ,
                cron_timezone: self.cron_timezone
                ,
                cron_starts_at: self.cron_starts_at
                ,
                cron_ends_at: self.cron_ends_at
                ,
                cron_next_run_at: self.cron_next_run_at
                ,
                cron_last_tick_at: self.cron_last_tick_at
                ,
                created_at: self.created_at
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("created_at", "created_at was not specified but it is required when building JobResource")
                    )?
                ,
                retired_at: self.retired_at
                ,
            }
        )
    }
}

