// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`CancelJob`](crate::operation::cancel_job::builders::CancelJobFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::cancel_job::builders::CancelJobFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::cancel_job::builders::CancelJobFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::cancel_job::builders::CancelJobFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::cancel_job::builders::CancelJobFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`job_id(impl Into<String>)`](crate::operation::cancel_job::builders::CancelJobFluentBuilder::job_id) / [`set_job_id(Option<String>)`](crate::operation::cancel_job::builders::CancelJobFluentBuilder::set_job_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`CancelJobOutput`](crate::operation::cancel_job::CancelJobOutput) with field(s):
    ///   - [`data(JobResource)`](crate::operation::cancel_job::CancelJobOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<CancelJobError>`](crate::operation::cancel_job::CancelJobError)
    pub fn cancel_job(&self) -> crate::operation::cancel_job::builders::CancelJobFluentBuilder {
                                crate::operation::cancel_job::builders::CancelJobFluentBuilder::new(self.handle.clone())
                            }
}

