// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`CreateEndpoint`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`name(impl Into<String>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::set_name):<br>required: **true**<br>(undocumented)<br>
    ///   - [`endpoint_type(EndpointTypeEnum)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::endpoint_type) / [`set_endpoint_type(Option<EndpointTypeEnum>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::set_endpoint_type):<br>required: **true**<br>(undocumented)<br>
    ///   - [`payload_spec(impl Into<String>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::payload_spec) / [`set_payload_spec(Option<String>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::set_payload_spec):<br>required: **false**<br>(undocumented)<br>
    ///   - [`config(impl Into<String>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::config) / [`set_config(Option<String>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::set_config):<br>required: **false**<br>(undocumented)<br>
    ///   - [`spec(Document)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::spec) / [`set_spec(Option<Document>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::set_spec):<br>required: **true**<br>(undocumented)<br>
    ///   - [`retry_policy(RetryPolicy)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::retry_policy) / [`set_retry_policy(Option<RetryPolicy>)`](crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::set_retry_policy):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`CreateEndpointOutput`](crate::operation::create_endpoint::CreateEndpointOutput) with field(s):
    ///   - [`data(EndpointResource)`](crate::operation::create_endpoint::CreateEndpointOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<CreateEndpointError>`](crate::operation::create_endpoint::CreateEndpointError)
    pub fn create_endpoint(&self) -> crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder {
                                crate::operation::create_endpoint::builders::CreateEndpointFluentBuilder::new(self.handle.clone())
                            }
}

