// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`CreatePayloadSpec`](crate::operation::create_payload_spec::builders::CreatePayloadSpecFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::create_payload_spec::builders::CreatePayloadSpecFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::create_payload_spec::builders::CreatePayloadSpecFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::create_payload_spec::builders::CreatePayloadSpecFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::create_payload_spec::builders::CreatePayloadSpecFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`name(impl Into<String>)`](crate::operation::create_payload_spec::builders::CreatePayloadSpecFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::create_payload_spec::builders::CreatePayloadSpecFluentBuilder::set_name):<br>required: **true**<br>(undocumented)<br>
    ///   - [`schema(Document)`](crate::operation::create_payload_spec::builders::CreatePayloadSpecFluentBuilder::schema) / [`set_schema(Option<Document>)`](crate::operation::create_payload_spec::builders::CreatePayloadSpecFluentBuilder::set_schema):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`CreatePayloadSpecOutput`](crate::operation::create_payload_spec::CreatePayloadSpecOutput) with field(s):
    ///   - [`data(PayloadSpecResource)`](crate::operation::create_payload_spec::CreatePayloadSpecOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<CreatePayloadSpecError>`](crate::operation::create_payload_spec::CreatePayloadSpecError)
    pub fn create_payload_spec(&self) -> crate::operation::create_payload_spec::builders::CreatePayloadSpecFluentBuilder {
                                crate::operation::create_payload_spec::builders::CreatePayloadSpecFluentBuilder::new(self.handle.clone())
                            }
}

