// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`UpdateEndpoint`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`name(impl Into<String>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::set_name):<br>required: **true**<br>(undocumented)<br>
    ///   - [`spec(Document)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::spec) / [`set_spec(Option<Document>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::set_spec):<br>required: **false**<br>(undocumented)<br>
    ///   - [`config(impl Into<String>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::config) / [`set_config(Option<String>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::set_config):<br>required: **false**<br>(undocumented)<br>
    ///   - [`payload_spec(impl Into<String>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::payload_spec) / [`set_payload_spec(Option<String>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::set_payload_spec):<br>required: **false**<br>(undocumented)<br>
    ///   - [`retry_policy(RetryPolicy)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::retry_policy) / [`set_retry_policy(Option<RetryPolicy>)`](crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::set_retry_policy):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`UpdateEndpointOutput`](crate::operation::update_endpoint::UpdateEndpointOutput) with field(s):
    ///   - [`data(EndpointResource)`](crate::operation::update_endpoint::UpdateEndpointOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<UpdateEndpointError>`](crate::operation::update_endpoint::UpdateEndpointError)
    pub fn update_endpoint(&self) -> crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder {
                                crate::operation::update_endpoint::builders::UpdateEndpointFluentBuilder::new(self.handle.clone())
                            }
}

