// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`CancelExecution`](crate::operation::cancel_execution::builders::CancelExecutionFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::cancel_execution::builders::CancelExecutionFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::cancel_execution::builders::CancelExecutionFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::cancel_execution::builders::CancelExecutionFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::cancel_execution::builders::CancelExecutionFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`execution_id(impl Into<String>)`](crate::operation::cancel_execution::builders::CancelExecutionFluentBuilder::execution_id) / [`set_execution_id(Option<String>)`](crate::operation::cancel_execution::builders::CancelExecutionFluentBuilder::set_execution_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`CancelExecutionOutput`](crate::operation::cancel_execution::CancelExecutionOutput) with field(s):
    ///   - [`data(ExecutionResource)`](crate::operation::cancel_execution::CancelExecutionOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<CancelExecutionError>`](crate::operation::cancel_execution::CancelExecutionError)
    pub fn cancel_execution(&self) -> crate::operation::cancel_execution::builders::CancelExecutionFluentBuilder {
                                crate::operation::cancel_execution::builders::CancelExecutionFluentBuilder::new(self.handle.clone())
                            }
}

