// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`CreateJob`](crate::operation::create_job::builders::CreateJobFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`endpoint(impl Into<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::endpoint) / [`set_endpoint(Option<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::set_endpoint):<br>required: **true**<br>(undocumented)<br>
    ///   - [`trigger(TriggerTypeEnum)`](crate::operation::create_job::builders::CreateJobFluentBuilder::trigger) / [`set_trigger(Option<TriggerTypeEnum>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::set_trigger):<br>required: **true**<br>(undocumented)<br>
    ///   - [`idempotency_key(impl Into<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::idempotency_key) / [`set_idempotency_key(Option<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::set_idempotency_key):<br>required: **false**<br>(undocumented)<br>
    ///   - [`input(Document)`](crate::operation::create_job::builders::CreateJobFluentBuilder::input) / [`set_input(Option<Document>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::set_input):<br>required: **false**<br>(undocumented)<br>
    ///   - [`run_at(DateTime)`](crate::operation::create_job::builders::CreateJobFluentBuilder::run_at) / [`set_run_at(Option<DateTime>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::set_run_at):<br>required: **false**<br>(undocumented)<br>
    ///   - [`cron(impl Into<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::cron) / [`set_cron(Option<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::set_cron):<br>required: **false**<br>(undocumented)<br>
    ///   - [`timezone(impl Into<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::timezone) / [`set_timezone(Option<String>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::set_timezone):<br>required: **false**<br>(undocumented)<br>
    ///   - [`starts_at(DateTime)`](crate::operation::create_job::builders::CreateJobFluentBuilder::starts_at) / [`set_starts_at(Option<DateTime>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::set_starts_at):<br>required: **false**<br>(undocumented)<br>
    ///   - [`ends_at(DateTime)`](crate::operation::create_job::builders::CreateJobFluentBuilder::ends_at) / [`set_ends_at(Option<DateTime>)`](crate::operation::create_job::builders::CreateJobFluentBuilder::set_ends_at):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`CreateJobOutput`](crate::operation::create_job::CreateJobOutput) with field(s):
    ///   - [`data(JobResource)`](crate::operation::create_job::CreateJobOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<CreateJobError>`](crate::operation::create_job::CreateJobError)
    pub fn create_job(&self) -> crate::operation::create_job::builders::CreateJobFluentBuilder {
                                crate::operation::create_job::builders::CreateJobFluentBuilder::new(self.handle.clone())
                            }
}

