// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`DeleteEndpoint`](crate::operation::delete_endpoint::builders::DeleteEndpointFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::delete_endpoint::builders::DeleteEndpointFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::delete_endpoint::builders::DeleteEndpointFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::delete_endpoint::builders::DeleteEndpointFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::delete_endpoint::builders::DeleteEndpointFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`name(impl Into<String>)`](crate::operation::delete_endpoint::builders::DeleteEndpointFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::delete_endpoint::builders::DeleteEndpointFluentBuilder::set_name):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`DeleteEndpointOutput`](crate::operation::delete_endpoint::DeleteEndpointOutput)
                            /// - On failure, responds with [`SdkError<DeleteEndpointError>`](crate::operation::delete_endpoint::DeleteEndpointError)
    pub fn delete_endpoint(&self) -> crate::operation::delete_endpoint::builders::DeleteEndpointFluentBuilder {
                                crate::operation::delete_endpoint::builders::DeleteEndpointFluentBuilder::new(self.handle.clone())
                            }
}

