// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`DeletePayloadSpec`](crate::operation::delete_payload_spec::builders::DeletePayloadSpecFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::delete_payload_spec::builders::DeletePayloadSpecFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::delete_payload_spec::builders::DeletePayloadSpecFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::delete_payload_spec::builders::DeletePayloadSpecFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::delete_payload_spec::builders::DeletePayloadSpecFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`name(impl Into<String>)`](crate::operation::delete_payload_spec::builders::DeletePayloadSpecFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::delete_payload_spec::builders::DeletePayloadSpecFluentBuilder::set_name):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`DeletePayloadSpecOutput`](crate::operation::delete_payload_spec::DeletePayloadSpecOutput)
                            /// - On failure, responds with [`SdkError<DeletePayloadSpecError>`](crate::operation::delete_payload_spec::DeletePayloadSpecError)
    pub fn delete_payload_spec(&self) -> crate::operation::delete_payload_spec::builders::DeletePayloadSpecFluentBuilder {
                                crate::operation::delete_payload_spec::builders::DeletePayloadSpecFluentBuilder::new(self.handle.clone())
                            }
}

