// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetPayloadSpec`](crate::operation::get_payload_spec::builders::GetPayloadSpecFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::get_payload_spec::builders::GetPayloadSpecFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::get_payload_spec::builders::GetPayloadSpecFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::get_payload_spec::builders::GetPayloadSpecFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::get_payload_spec::builders::GetPayloadSpecFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`name(impl Into<String>)`](crate::operation::get_payload_spec::builders::GetPayloadSpecFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::get_payload_spec::builders::GetPayloadSpecFluentBuilder::set_name):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetPayloadSpecOutput`](crate::operation::get_payload_spec::GetPayloadSpecOutput) with field(s):
    ///   - [`data(PayloadSpecResource)`](crate::operation::get_payload_spec::GetPayloadSpecOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<GetPayloadSpecError>`](crate::operation::get_payload_spec::GetPayloadSpecError)
    pub fn get_payload_spec(&self) -> crate::operation::get_payload_spec::builders::GetPayloadSpecFluentBuilder {
                                crate::operation::get_payload_spec::builders::GetPayloadSpecFluentBuilder::new(self.handle.clone())
                            }
}

