// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetJobVersions`](crate::operation::get_job_versions::builders::GetJobVersionsFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::get_job_versions::builders::GetJobVersionsFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::get_job_versions::builders::GetJobVersionsFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::get_job_versions::builders::GetJobVersionsFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::get_job_versions::builders::GetJobVersionsFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`job_id(impl Into<String>)`](crate::operation::get_job_versions::builders::GetJobVersionsFluentBuilder::job_id) / [`set_job_id(Option<String>)`](crate::operation::get_job_versions::builders::GetJobVersionsFluentBuilder::set_job_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetJobVersionsOutput`](crate::operation::get_job_versions::GetJobVersionsOutput) with field(s):
    ///   - [`data(Vec::<JobResource>)`](crate::operation::get_job_versions::GetJobVersionsOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<GetJobVersionsError>`](crate::operation::get_job_versions::GetJobVersionsError)
    pub fn get_job_versions(&self) -> crate::operation::get_job_versions::builders::GetJobVersionsFluentBuilder {
                                crate::operation::get_job_versions::builders::GetJobVersionsFluentBuilder::new(self.handle.clone())
                            }
}

