// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetJobStatus`](crate::operation::get_job_status::builders::GetJobStatusFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::get_job_status::builders::GetJobStatusFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::get_job_status::builders::GetJobStatusFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::get_job_status::builders::GetJobStatusFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::get_job_status::builders::GetJobStatusFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`job_id(impl Into<String>)`](crate::operation::get_job_status::builders::GetJobStatusFluentBuilder::job_id) / [`set_job_id(Option<String>)`](crate::operation::get_job_status::builders::GetJobStatusFluentBuilder::set_job_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetJobStatusOutput`](crate::operation::get_job_status::GetJobStatusOutput) with field(s):
    ///   - [`data(JobStatusResponse)`](crate::operation::get_job_status::GetJobStatusOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<GetJobStatusError>`](crate::operation::get_job_status::GetJobStatusError)
    pub fn get_job_status(&self) -> crate::operation::get_job_status::builders::GetJobStatusFluentBuilder {
                                crate::operation::get_job_status::builders::GetJobStatusFluentBuilder::new(self.handle.clone())
                            }
}

