// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListJobs`](crate::operation::list_jobs::builders::ListJobsFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`cursor(impl Into<String>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::cursor) / [`set_cursor(Option<String>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::set_cursor):<br>required: **false**<br>(undocumented)<br>
    ///   - [`limit(i32)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::limit) / [`set_limit(Option<i32>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::set_limit):<br>required: **false**<br>(undocumented)<br>
    ///   - [`job_id(impl Into<String>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::job_id) / [`set_job_id(Option<String>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::set_job_id):<br>required: **false**<br>Exact-match job id filter.<br>
    ///   - [`endpoint(impl Into<String>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::endpoint) / [`set_endpoint(Option<String>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::set_endpoint):<br>required: **false**<br>(undocumented)<br>
    ///   - [`trigger_type(TriggerTypeEnum)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::trigger_type) / [`set_trigger_type(Option<Vec::<TriggerTypeEnum>>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::set_trigger_type):<br>required: **false**<br>(undocumented)<br>
    ///   - [`status(JobStatusEnum)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::status) / [`set_status(Option<Vec::<JobStatusEnum>>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::set_status):<br>required: **false**<br>(undocumented)<br>
    ///   - [`endpoint_type(EndpointTypeEnum)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::endpoint_type) / [`set_endpoint_type(Option<Vec::<EndpointTypeEnum>>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::set_endpoint_type):<br>required: **false**<br>(undocumented)<br>
    ///   - [`created_after(DateTime)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::created_after) / [`set_created_after(Option<DateTime>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::set_created_after):<br>required: **false**<br>Inclusive lower bound on `created_at` (RFC-3339).<br>
    ///   - [`created_before(DateTime)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::created_before) / [`set_created_before(Option<DateTime>)`](crate::operation::list_jobs::builders::ListJobsFluentBuilder::set_created_before):<br>required: **false**<br>Inclusive upper bound on `created_at` (RFC-3339).<br>
                            /// - On success, responds with [`ListJobsOutput`](crate::operation::list_jobs::ListJobsOutput) with field(s):
    ///   - [`data(Vec::<JobSummary>)`](crate::operation::list_jobs::ListJobsOutput::data): (undocumented)
    ///   - [`cursor(Option<String>)`](crate::operation::list_jobs::ListJobsOutput::cursor): (undocumented)
                            /// - On failure, responds with [`SdkError<ListJobsError>`](crate::operation::list_jobs::ListJobsError)
    pub fn list_jobs(&self) -> crate::operation::list_jobs::builders::ListJobsFluentBuilder {
                                crate::operation::list_jobs::builders::ListJobsFluentBuilder::new(self.handle.clone())
                            }
}

