// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListEndpoints`](crate::operation::list_endpoints::builders::ListEndpointsFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::list_endpoints::builders::ListEndpointsFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::list_endpoints::builders::ListEndpointsFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::list_endpoints::builders::ListEndpointsFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::list_endpoints::builders::ListEndpointsFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`cursor(impl Into<String>)`](crate::operation::list_endpoints::builders::ListEndpointsFluentBuilder::cursor) / [`set_cursor(Option<String>)`](crate::operation::list_endpoints::builders::ListEndpointsFluentBuilder::set_cursor):<br>required: **false**<br>(undocumented)<br>
    ///   - [`limit(i32)`](crate::operation::list_endpoints::builders::ListEndpointsFluentBuilder::limit) / [`set_limit(Option<i32>)`](crate::operation::list_endpoints::builders::ListEndpointsFluentBuilder::set_limit):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`ListEndpointsOutput`](crate::operation::list_endpoints::ListEndpointsOutput) with field(s):
    ///   - [`data(Vec::<EndpointResource>)`](crate::operation::list_endpoints::ListEndpointsOutput::data): (undocumented)
    ///   - [`cursor(Option<String>)`](crate::operation::list_endpoints::ListEndpointsOutput::cursor): (undocumented)
                            /// - On failure, responds with [`SdkError<ListEndpointsError>`](crate::operation::list_endpoints::ListEndpointsError)
    pub fn list_endpoints(&self) -> crate::operation::list_endpoints::builders::ListEndpointsFluentBuilder {
                                crate::operation::list_endpoints::builders::ListEndpointsFluentBuilder::new(self.handle.clone())
                            }
}

