// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListExecutionLogs`](crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`cursor(impl Into<String>)`](crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder::cursor) / [`set_cursor(Option<String>)`](crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder::set_cursor):<br>required: **false**<br>(undocumented)<br>
    ///   - [`limit(i32)`](crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder::limit) / [`set_limit(Option<i32>)`](crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder::set_limit):<br>required: **false**<br>(undocumented)<br>
    ///   - [`execution_id(impl Into<String>)`](crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder::execution_id) / [`set_execution_id(Option<String>)`](crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder::set_execution_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`ListExecutionLogsOutput`](crate::operation::list_execution_logs::ListExecutionLogsOutput) with field(s):
    ///   - [`data(Vec::<ExecutionLogResource>)`](crate::operation::list_execution_logs::ListExecutionLogsOutput::data): (undocumented)
    ///   - [`cursor(Option<String>)`](crate::operation::list_execution_logs::ListExecutionLogsOutput::cursor): (undocumented)
                            /// - On failure, responds with [`SdkError<ListExecutionLogsError>`](crate::operation::list_execution_logs::ListExecutionLogsError)
    pub fn list_execution_logs(&self) -> crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder {
                                crate::operation::list_execution_logs::builders::ListExecutionLogsFluentBuilder::new(self.handle.clone())
                            }
}

