// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListExecutionAttempts`](crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`cursor(impl Into<String>)`](crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder::cursor) / [`set_cursor(Option<String>)`](crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder::set_cursor):<br>required: **false**<br>(undocumented)<br>
    ///   - [`limit(i32)`](crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder::limit) / [`set_limit(Option<i32>)`](crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder::set_limit):<br>required: **false**<br>(undocumented)<br>
    ///   - [`execution_id(impl Into<String>)`](crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder::execution_id) / [`set_execution_id(Option<String>)`](crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder::set_execution_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`ListExecutionAttemptsOutput`](crate::operation::list_execution_attempts::ListExecutionAttemptsOutput) with field(s):
    ///   - [`data(Vec::<AttemptResource>)`](crate::operation::list_execution_attempts::ListExecutionAttemptsOutput::data): (undocumented)
    ///   - [`cursor(Option<String>)`](crate::operation::list_execution_attempts::ListExecutionAttemptsOutput::cursor): (undocumented)
                            /// - On failure, responds with [`SdkError<ListExecutionAttemptsError>`](crate::operation::list_execution_attempts::ListExecutionAttemptsError)
    pub fn list_execution_attempts(&self) -> crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder {
                                crate::operation::list_execution_attempts::builders::ListExecutionAttemptsFluentBuilder::new(self.handle.clone())
                            }
}

