// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`UpdateJob`](crate::operation::update_job::builders::UpdateJobFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`org_id(impl Into<String>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`job_id(impl Into<String>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::job_id) / [`set_job_id(Option<String>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::set_job_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`cron(impl Into<String>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::cron) / [`set_cron(Option<String>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::set_cron):<br>required: **false**<br>(undocumented)<br>
    ///   - [`timezone(impl Into<String>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::timezone) / [`set_timezone(Option<String>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::set_timezone):<br>required: **false**<br>(undocumented)<br>
    ///   - [`input(Document)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::input) / [`set_input(Option<Document>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::set_input):<br>required: **false**<br>(undocumented)<br>
    ///   - [`starts_at(DateTime)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::starts_at) / [`set_starts_at(Option<DateTime>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::set_starts_at):<br>required: **false**<br>(undocumented)<br>
    ///   - [`ends_at(DateTime)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::ends_at) / [`set_ends_at(Option<DateTime>)`](crate::operation::update_job::builders::UpdateJobFluentBuilder::set_ends_at):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`UpdateJobOutput`](crate::operation::update_job::UpdateJobOutput) with field(s):
    ///   - [`data(JobResource)`](crate::operation::update_job::UpdateJobOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<UpdateJobError>`](crate::operation::update_job::UpdateJobError)
    pub fn update_job(&self) -> crate::operation::update_job::builders::UpdateJobFluentBuilder {
                                crate::operation::update_job::builders::UpdateJobFluentBuilder::new(self.handle.clone())
                            }
}

