#!/usr/bin/env bash
# Starts a prod-like Invokr environment in Docker with KMS support.
# Two-phase startup: infra + init → app services with encrypted env vars.

set -euo pipefail

COMPOSE_FILE="docker-compose.prod.yml"
ENV_FILE=".env.prod.kms"
DC="docker compose -f $COMPOSE_FILE"

# ── Phase 1: Build + Infrastructure ──────────────────────────

echo "==> Building all images..."
$DC build

echo ""
echo "==> Starting infrastructure (postgres, localstack, mock-server)..."
$DC up -d postgres localstack invokr-mock-server

echo ""
echo "==> Waiting for PostgreSQL..."
until $DC exec -T postgres pg_isready -U invokr -d invokr_db > /dev/null 2>&1; do
    sleep 1
done
echo "    PostgreSQL ready."

echo ""
echo "==> Waiting for LocalStack..."
until $DC exec -T localstack curl -sf http://localhost:4566/_localstack/health > /dev/null 2>&1; do
    sleep 1
done
echo "    LocalStack ready."

echo ""
echo "==> Running database migrations..."
$DC exec -T postgres sh -c '
    PGPASSWORD=invokr psql -h localhost -U invokr -d invokr_db -f /migrations/20260317000000_initial.sql &&
    PGPASSWORD=invokr psql -h localhost -U invokr -d invokr_db -f /migrations/20260318000000_multi_tenancy.sql &&
    PGPASSWORD=invokr psql -h localhost -U invokr -d invokr_db -f /migrations/20260322000000_txn_based_pickup.sql &&
    PGPASSWORD=invokr psql -h localhost -U invokr -d invokr_db -f /migrations/20260322000001_pg_cron.sql
'
echo "    Migrations applied."

# ── Phase 2: KMS init + encrypt + start apps ─────────────────

echo ""
echo "==> Creating KMS key..."
KMS_OUTPUT=$($DC exec -T localstack awslocal kms create-key \
    --region us-east-1 \
    --description "Invokr prod-like key" \
    --query 'KeyMetadata.KeyId' \
    --output text)
KEY_ID=$(echo "$KMS_OUTPUT" | tr -d '[:space:]')

if [ -z "$KEY_ID" ]; then
    echo "ERROR: Failed to create KMS key. Output:"
    echo "$KMS_OUTPUT"
    exit 1
fi

$DC exec -T localstack awslocal kms create-alias \
    --region us-east-1 \
    --alias-name alias/invokr-prod \
    --target-key-id "$KEY_ID" 2>/dev/null || true

echo "    Key ID: $KEY_ID"

echo ""
echo "==> Encrypting sensitive values..."

encrypt_value() {
    local plaintext="$1"
    $DC exec -T localstack awslocal kms encrypt \
        --region us-east-1 \
        --key-id "$KEY_ID" \
        --plaintext "$plaintext" \
        --query 'CiphertextBlob' \
        --output text
}

# DB URL uses Docker-internal hostname
ENC_DB_URL=$(encrypt_value "postgresql://invokr:invokr@postgres:5432/invokr_db")
echo "    INVOKR_DATABASE_URL      encrypted"

ENC_API_KEY=$(encrypt_value "dev-api-key")
echo "    INVOKR_API_KEY           encrypted"

ENC_ENCRYPTION_KEY=$(encrypt_value "0000000000000000000000000000000000000000000000000000000000000000")
echo "    INVOKR_ENCRYPTION_KEY    encrypted"

echo ""
echo "==> Writing $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Generated by scripts/docker-prod.sh — do not edit
INVOKR_KMS_ENABLED=true

# Encrypted values (base64-encoded KMS ciphertext)
INVOKR_DATABASE_URL=$ENC_DB_URL
INVOKR_API_KEY=$ENC_API_KEY
INVOKR_ENCRYPTION_KEY=$ENC_ENCRYPTION_KEY

# Non-sensitive config
INVOKR_DB_POOL_SIZE=20
INVOKR_WORKER_MAX_CONCURRENT=50
INVOKR_WORKER_POLL_INTERVAL_MS=200
INVOKR_CONFIG_CACHE_TTL_SEC=60
INVOKR_SECRET_CACHE_TTL_SEC=300
INVOKR_WORKER_SHUTDOWN_TIMEOUT_SEC=30

# AWS / LocalStack (Docker-internal)
AWS_ENDPOINT_URL=http://localstack:4566
AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=test
AWS_SECRET_ACCESS_KEY=test
EOF
echo "    Done."

echo ""
echo "==> Starting application services (server, worker)..."
$DC up -d invokr-server invokr-worker

echo ""
echo "==> Waiting for API health..."
for i in $(seq 1 30); do
    if curl -sf http://localhost:8080/invokr/health > /dev/null 2>&1; then
        echo "    API ready."
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo "ERROR: API failed to start within 30s"
        $DC logs invokr-server
        exit 1
    fi
    sleep 1
done

echo ""
echo "==> Waiting for Dashboard health..."
for i in $(seq 1 30); do
    if curl -sf http://localhost:8080/dashboard/ > /dev/null 2>&1; then
        echo "    Dashboard ready."
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo "WARNING: Dashboard failed to start within 30s (continuing anyway)"
        $DC logs invokr-server
        break
    fi
    sleep 1
done

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  Invokr prod-like environment is running!"
echo "════════════════════════════════════════════════════════════"
echo "  API:          http://localhost:8080/invokr"
echo "  Dashboard:    http://localhost:8080/dashboard"
echo "  Mock Server:  http://localhost:9999"
echo "  Worker:       metrics on :9090"
echo "  PostgreSQL:   localhost:5432"
echo "  LocalStack:   http://localhost:4566"
echo ""
echo "  KMS:          enabled (key: ${KEY_ID})"
echo ""
echo "  Next steps:"
echo "    INVOKR_BASE_URL=http://localhost:8080/invokr ./scripts/setup-dev-tenant.sh"
echo "    INVOKR_URL=http://localhost:8080/invokr just test-immediate"
echo ""
echo "  Teardown:"
echo "    just docker-prod-down"
echo "════════════════════════════════════════════════════════════"
