#!/usr/bin/env bash
# Creates a KMS key on LocalStack, encrypts all sensitive env vars, and writes .env.kms
# Usage: ./scripts/kms-init.sh

set -euo pipefail

ENDPOINT="${AWS_ENDPOINT_URL:-http://localhost:4566}"
REGION="${AWS_REGION:-us-east-1}"
ALIAS="alias/kronos-dev"

export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-test}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-test}"
export AWS_DEFAULT_REGION="$REGION"

encrypt_value() {
    local key_id="$1"
    local plaintext="$2"
    aws kms encrypt \
        --endpoint-url "$ENDPOINT" \
        --region "$REGION" \
        --key-id "$key_id" \
        --plaintext "$plaintext" \
        --cli-binary-format raw-in-base64-out \
        --query 'CiphertextBlob' \
        --output text
}

echo "==> Creating KMS key on $ENDPOINT ..."

KEY_ID=$(aws kms create-key \
    --endpoint-url "$ENDPOINT" \
    --region "$REGION" \
    --description "Kronos dev encryption key" \
    --query 'KeyMetadata.KeyId' \
    --output text)

echo "    Key ID: $KEY_ID"

# Create an alias for convenience (ignore error if it already exists)
aws kms create-alias \
    --endpoint-url "$ENDPOINT" \
    --region "$REGION" \
    --alias-name "$ALIAS" \
    --target-key-id "$KEY_ID" 2>/dev/null || true

echo "    Alias:  $ALIAS"

# Save key ID for other scripts
echo "$KEY_ID" > .kms-key-id
echo "    Saved key ID to .kms-key-id"

# Plaintext values to encrypt
DB_URL="${TE_DATABASE_URL:-postgresql://kronos:kronos@localhost:5432/taskexecutor}"
API_KEY="${TE_API_KEY:-dev-api-key}"
ENCRYPTION_KEY="${TE_ENCRYPTION_KEY:-0000000000000000000000000000000000000000000000000000000000000000}"

echo ""
echo "==> Encrypting sensitive env vars ..."

ENCRYPTED_DB_URL=$(encrypt_value "$KEY_ID" "$DB_URL")
echo "    TE_DATABASE_URL    encrypted"

ENCRYPTED_API_KEY=$(encrypt_value "$KEY_ID" "$API_KEY")
echo "    TE_API_KEY         encrypted"

ENCRYPTED_ENCRYPTION_KEY=$(encrypt_value "$KEY_ID" "$ENCRYPTION_KEY")
echo "    TE_ENCRYPTION_KEY  encrypted"

# Write .env.kms
cat > .env.kms <<EOF
# Generated by scripts/kms-init.sh — KMS-enabled dev environment
# Copy to .env or source before running: cargo run --features kms -p kronos-api

TE_KMS_ENABLED=true

# Encrypted values (base64-encoded KMS ciphertext)
TE_DATABASE_URL=$ENCRYPTED_DB_URL
TE_API_KEY=$ENCRYPTED_API_KEY
TE_ENCRYPTION_KEY=$ENCRYPTED_ENCRYPTION_KEY

# Non-sensitive values (plaintext)
TE_LISTEN_ADDR=0.0.0.0:8080
TE_DB_POOL_SIZE=20
TE_WORKER_MAX_CONCURRENT=50
TE_WORKER_POLL_INTERVAL_MS=200
TE_CONFIG_CACHE_TTL_SEC=60
TE_SECRET_CACHE_TTL_SEC=300
TE_WORKER_SHUTDOWN_TIMEOUT_SEC=30

# AWS / LocalStack
AWS_ENDPOINT_URL=$ENDPOINT
AWS_REGION=$REGION
AWS_ACCESS_KEY_ID=test
AWS_SECRET_ACCESS_KEY=test

# CLI / Test Scripts (set after creating an org + workspace via the API)
# KRONOS_ORG_ID=
# KRONOS_WORKSPACE_ID=
EOF

echo ""
echo "==> Wrote .env.kms"
echo ""
echo "To use:  cp .env.kms .env && cargo run --features kms -p kronos-api"
echo "Or:      just kms-dev"
