// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::update_job::_update_job_input::UpdateJobInputBuilder;

pub use crate::operation::update_job::_update_job_output::UpdateJobOutputBuilder;

impl crate::operation::update_job::builders::UpdateJobInputBuilder {
                    /// Sends a request with this input using the given client.
                    pub async fn send_with(self, client: &crate::Client) -> ::std::result::Result<
                        crate::operation::update_job::UpdateJobOutput,
                        ::aws_smithy_runtime_api::client::result::SdkError<
                            crate::operation::update_job::UpdateJobError,
                            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse
                        >
                    > {
                        let mut fluent_builder = client.update_job();
                        fluent_builder.inner = self;
                        fluent_builder.send().await
                    }
                }
/// Fluent builder constructing a request to `UpdateJob`.
/// 
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct UpdateJobFluentBuilder {
                handle: ::std::sync::Arc<crate::client::Handle>,
                inner: crate::operation::update_job::builders::UpdateJobInputBuilder,
config_override: ::std::option::Option<crate::config::Builder>,
            }
impl
                crate::client::customize::internal::CustomizableSend<
                    crate::operation::update_job::UpdateJobOutput,
                    crate::operation::update_job::UpdateJobError,
                > for UpdateJobFluentBuilder
            {
                fn send(
                    self,
                    config_override: crate::config::Builder,
                ) -> crate::client::customize::internal::BoxFuture<
                    crate::client::customize::internal::SendResult<
                        crate::operation::update_job::UpdateJobOutput,
                        crate::operation::update_job::UpdateJobError,
                    >,
                > {
                    ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
                }
            }
impl UpdateJobFluentBuilder {
    /// Creates a new `UpdateJobFluentBuilder`.
                    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
                        Self {
                            handle,
                            inner: ::std::default::Default::default(),
    config_override: ::std::option::Option::None,
                        }
                    }
    /// Access the UpdateJob as a reference.
                    pub fn as_input(&self) -> &crate::operation::update_job::builders::UpdateJobInputBuilder {
                        &self.inner
                    }
    /// Sends the request and returns the response.
                    ///
                    /// If an error occurs, an `SdkError` will be returned with additional details that
                    /// can be matched against.
                    ///
                    /// By default, any retryable failures will be retried twice. Retry behavior
                    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
                    /// set when configuring the client.
                    pub async fn send(self) -> ::std::result::Result<crate::operation::update_job::UpdateJobOutput, ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::update_job::UpdateJobError, ::aws_smithy_runtime_api::client::orchestrator::HttpResponse>> {
                        let input = self.inner.build().map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
                        let runtime_plugins = crate::operation::update_job::UpdateJob::operation_runtime_plugins(
                            self.handle.runtime_plugins.clone(),
                            &self.handle.conf,
                            self.config_override,
                        );
                        crate::operation::update_job::UpdateJob::orchestrate(&runtime_plugins, input).await
                    }
    
                    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
                    pub fn customize(
                        self,
                    ) -> crate::client::customize::CustomizableOperation<crate::operation::update_job::UpdateJobOutput, crate::operation::update_job::UpdateJobError, Self> {
                        crate::client::customize::CustomizableOperation::new(self)
                    }
    pub(crate) fn config_override(
                            mut self,
                            config_override: impl ::std::convert::Into<crate::config::Builder>,
                        ) -> Self {
                            self.set_config_override(::std::option::Option::Some(config_override.into()));
                            self
                        }
    
                        pub(crate) fn set_config_override(
                            &mut self,
                            config_override: ::std::option::Option<crate::config::Builder>,
                        ) -> &mut Self {
                            self.config_override = config_override;
                            self
                        }
    #[allow(missing_docs)] // documentation missing in model
    pub fn org_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.org_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_org_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_org_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_org_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_org_id()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn workspace_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.workspace_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_workspace_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_workspace_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_workspace_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_workspace_id()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn job_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.job_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_job_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_job_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_job_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_job_id()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.cron(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cron(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_cron(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cron(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_cron()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn timezone(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.timezone(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_timezone(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_timezone(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_timezone(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_timezone()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn input(mut self, input: ::aws_smithy_types::Document) -> Self {
                    self.inner = self.inner.input(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_input(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
                    self.inner = self.inner.set_input(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_input(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
                    self.inner.get_input()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn starts_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
                    self.inner = self.inner.starts_at(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_starts_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
                    self.inner = self.inner.set_starts_at(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_starts_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
                    self.inner.get_starts_at()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn ends_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
                    self.inner = self.inner.ends_at(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_ends_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
                    self.inner = self.inner.set_ends_at(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_ends_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
                    self.inner.get_ends_at()
                }
}

