// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CreateJobOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub data: crate::types::JobResource,
}
impl  CreateJobOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn data(&self) -> &crate::types::JobResource {
        &self.data
    }
}
impl CreateJobOutput {
    /// Creates a new builder-style object to manufacture [`CreateJobOutput`](crate::operation::create_job::CreateJobOutput).
    pub fn builder() -> crate::operation::create_job::builders::CreateJobOutputBuilder {
        crate::operation::create_job::builders::CreateJobOutputBuilder::default()
    }
}

/// A builder for [`CreateJobOutput`](crate::operation::create_job::CreateJobOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CreateJobOutputBuilder {
    pub(crate) data: ::std::option::Option<crate::types::JobResource>,
}
impl CreateJobOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn data(mut self, input: crate::types::JobResource) -> Self {
        self.data = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_data(mut self, input: ::std::option::Option<crate::types::JobResource>) -> Self {
        self.data = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_data(&self) -> &::std::option::Option<crate::types::JobResource> {
        &self.data
    }
    /// Consumes the builder and constructs a [`CreateJobOutput`](crate::operation::create_job::CreateJobOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`data`](crate::operation::create_job::builders::CreateJobOutputBuilder::data)
    pub fn build(self) -> ::std::result::Result<crate::operation::create_job::CreateJobOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::create_job::CreateJobOutput {
                data: self.data
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("data", "data was not specified but it is required when building CreateJobOutput")
                    )?
                ,
            }
        )
    }
}

