// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub fn de_delete_payload_spec_http_error(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::delete_payload_spec::DeletePayloadSpecOutput, crate::operation::delete_payload_spec::DeletePayloadSpecError> {
    #[allow(unused_mut)]
    let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body).map_err(crate::operation::delete_payload_spec::DeletePayloadSpecError::unhandled)?;
    let generic = generic_builder.build();
    let error_code = match generic.code() {
                                Some(code) => code,
                                None => return Err(crate::operation::delete_payload_spec::DeletePayloadSpecError::unhandled(generic))
                            };
    
                            let _error_message = generic.message().map(|msg|msg.to_owned());
    Err(match error_code {
        "NotFoundError" => crate::operation::delete_payload_spec::DeletePayloadSpecError::NotFoundError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::NotFoundErrorBuilder::default();
                    output = crate::protocol_serde::shape_not_found_error::de_not_found_error_json_err(_response_body, output).map_err(crate::operation::delete_payload_spec::DeletePayloadSpecError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::not_found_error_correct_errors(output).build().map_err(crate::operation::delete_payload_spec::DeletePayloadSpecError::unhandled)?
                }
            ;
            if tmp.message.is_none() {
                                                            tmp.message = _error_message;
                                                        }
            tmp
        }),
        "UnauthorizedError" => crate::operation::delete_payload_spec::DeletePayloadSpecError::UnauthorizedError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::UnauthorizedErrorBuilder::default();
                    output = crate::protocol_serde::shape_unauthorized_error::de_unauthorized_error_json_err(_response_body, output).map_err(crate::operation::delete_payload_spec::DeletePayloadSpecError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::unauthorized_error_correct_errors(output).build().map_err(crate::operation::delete_payload_spec::DeletePayloadSpecError::unhandled)?
                }
            ;
            if tmp.message.is_none() {
                                                            tmp.message = _error_message;
                                                        }
            tmp
        }),
        "InternalError" => crate::operation::delete_payload_spec::DeletePayloadSpecError::InternalError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::InternalErrorBuilder::default();
                    output = crate::protocol_serde::shape_internal_error::de_internal_error_json_err(_response_body, output).map_err(crate::operation::delete_payload_spec::DeletePayloadSpecError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::internal_error_correct_errors(output).build().map_err(crate::operation::delete_payload_spec::DeletePayloadSpecError::unhandled)?
                }
            ;
            if tmp.message.is_none() {
                                                            tmp.message = _error_message;
                                                        }
            tmp
        }),
        "RateLimitedError" => crate::operation::delete_payload_spec::DeletePayloadSpecError::RateLimitedError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::RateLimitedErrorBuilder::default();
                    output = crate::protocol_serde::shape_rate_limited_error::de_rate_limited_error_json_err(_response_body, output).map_err(crate::operation::delete_payload_spec::DeletePayloadSpecError::unhandled)?;
                    let output = output.meta(generic);
                    crate::serde_util::rate_limited_error_correct_errors(output).build().map_err(crate::operation::delete_payload_spec::DeletePayloadSpecError::unhandled)?
                }
            ;
            if tmp.message.is_none() {
                                                            tmp.message = _error_message;
                                                        }
            tmp
        }),
        _ => crate::operation::delete_payload_spec::DeletePayloadSpecError::generic(generic)
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn de_delete_payload_spec_http_response(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::delete_payload_spec::DeletePayloadSpecOutput, crate::operation::delete_payload_spec::DeletePayloadSpecError> {
    Ok({
        #[allow(unused_mut)]
        let mut output = crate::operation::delete_payload_spec::builders::DeletePayloadSpecOutputBuilder::default();
        output.build()
    })
}

pub fn ser_delete_payload_spec_headers(
                    input: &crate::operation::delete_payload_spec::DeletePayloadSpecInput,
                    mut builder: ::http::request::Builder
                ) -> std::result::Result<::http::request::Builder, ::aws_smithy_types::error::operation::BuildError> {
    if let ::std::option::Option::Some(inner_1) = &input.org_id {
        let formatted_2 = inner_1.as_str();
        let header_value = formatted_2;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("org_id", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-org-id", header_value);
    }
    if let ::std::option::Option::Some(inner_3) = &input.workspace_id {
        let formatted_4 = inner_3.as_str();
        let header_value = formatted_4;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("workspace_id", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-workspace-id", header_value);
    }
    Ok(builder)
}

