// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CreateJobInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub org_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub workspace_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub endpoint: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub trigger: ::std::option::Option<crate::types::TriggerTypeEnum>,
    #[allow(missing_docs)] // documentation missing in model
    pub idempotency_key: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub input: ::std::option::Option<::aws_smithy_types::Document>,
    #[allow(missing_docs)] // documentation missing in model
    pub run_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub cron: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub timezone: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub starts_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub ends_at: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl  CreateJobInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn org_id(&self) -> ::std::option::Option<&str> {
        self.org_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn workspace_id(&self) -> ::std::option::Option<&str> {
        self.workspace_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint(&self) -> ::std::option::Option<&str> {
        self.endpoint.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn trigger(&self) -> ::std::option::Option<&crate::types::TriggerTypeEnum> {
        self.trigger.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn idempotency_key(&self) -> ::std::option::Option<&str> {
        self.idempotency_key.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn input(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.input.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn run_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.run_at.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron(&self) -> ::std::option::Option<&str> {
        self.cron.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn timezone(&self) -> ::std::option::Option<&str> {
        self.timezone.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn starts_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.starts_at.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn ends_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.ends_at.as_ref()
    }
}
impl CreateJobInput {
    /// Creates a new builder-style object to manufacture [`CreateJobInput`](crate::operation::create_job::CreateJobInput).
    pub fn builder() -> crate::operation::create_job::builders::CreateJobInputBuilder {
        crate::operation::create_job::builders::CreateJobInputBuilder::default()
    }
}

/// A builder for [`CreateJobInput`](crate::operation::create_job::CreateJobInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CreateJobInputBuilder {
    pub(crate) org_id: ::std::option::Option<::std::string::String>,
    pub(crate) workspace_id: ::std::option::Option<::std::string::String>,
    pub(crate) endpoint: ::std::option::Option<::std::string::String>,
    pub(crate) trigger: ::std::option::Option<crate::types::TriggerTypeEnum>,
    pub(crate) idempotency_key: ::std::option::Option<::std::string::String>,
    pub(crate) input: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) run_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) cron: ::std::option::Option<::std::string::String>,
    pub(crate) timezone: ::std::option::Option<::std::string::String>,
    pub(crate) starts_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) ends_at: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl CreateJobInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn org_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.org_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_org_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.org_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_org_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.org_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn workspace_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.workspace_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_workspace_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.workspace_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_workspace_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.workspace_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn endpoint(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.endpoint = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_endpoint(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.endpoint = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_endpoint(&self) -> &::std::option::Option<::std::string::String> {
        &self.endpoint
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn trigger(mut self, input: crate::types::TriggerTypeEnum) -> Self {
        self.trigger = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_trigger(mut self, input: ::std::option::Option<crate::types::TriggerTypeEnum>) -> Self {
        self.trigger = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_trigger(&self) -> &::std::option::Option<crate::types::TriggerTypeEnum> {
        &self.trigger
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn idempotency_key(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.idempotency_key = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_idempotency_key(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.idempotency_key = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_idempotency_key(&self) -> &::std::option::Option<::std::string::String> {
        &self.idempotency_key
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn input(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.input = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_input(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.input = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_input(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.input
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn run_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.run_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_run_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.run_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_run_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.run_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cron(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.cron = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cron(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.cron = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cron(&self) -> &::std::option::Option<::std::string::String> {
        &self.cron
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn timezone(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.timezone = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_timezone(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.timezone = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_timezone(&self) -> &::std::option::Option<::std::string::String> {
        &self.timezone
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn starts_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.starts_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_starts_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.starts_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_starts_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.starts_at
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn ends_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.ends_at = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_ends_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.ends_at = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_ends_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.ends_at
    }
    /// Consumes the builder and constructs a [`CreateJobInput`](crate::operation::create_job::CreateJobInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::create_job::CreateJobInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::create_job::CreateJobInput {
                org_id: self.org_id
                ,
                workspace_id: self.workspace_id
                ,
                endpoint: self.endpoint
                ,
                trigger: self.trigger
                ,
                idempotency_key: self.idempotency_key
                ,
                input: self.input
                ,
                run_at: self.run_at
                ,
                cron: self.cron
                ,
                timezone: self.timezone
                ,
                starts_at: self.starts_at
                ,
                ends_at: self.ends_at
                ,
            }
        )
    }
}

