// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetJobVersionsOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub data: ::std::vec::Vec::<crate::types::JobResource>,
}
impl  GetJobVersionsOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn data(&self) -> &[crate::types::JobResource] {
        use std::ops::Deref; self.data.deref()
    }
}
impl GetJobVersionsOutput {
    /// Creates a new builder-style object to manufacture [`GetJobVersionsOutput`](crate::operation::get_job_versions::GetJobVersionsOutput).
    pub fn builder() -> crate::operation::get_job_versions::builders::GetJobVersionsOutputBuilder {
        crate::operation::get_job_versions::builders::GetJobVersionsOutputBuilder::default()
    }
}

/// A builder for [`GetJobVersionsOutput`](crate::operation::get_job_versions::GetJobVersionsOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GetJobVersionsOutputBuilder {
    pub(crate) data: ::std::option::Option<::std::vec::Vec::<crate::types::JobResource>>,
}
impl GetJobVersionsOutputBuilder {
    /// Appends an item to `data`.
    ///
    /// To override the contents of this collection use [`set_data`](Self::set_data).
    ///
    pub fn data(mut self, input: crate::types::JobResource) -> Self {
        let mut v = self.data.unwrap_or_default();
                        v.push(input);
                        self.data = ::std::option::Option::Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_data(mut self, input: ::std::option::Option<::std::vec::Vec::<crate::types::JobResource>>) -> Self {
        self.data = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_data(&self) -> &::std::option::Option<::std::vec::Vec::<crate::types::JobResource>> {
        &self.data
    }
    /// Consumes the builder and constructs a [`GetJobVersionsOutput`](crate::operation::get_job_versions::GetJobVersionsOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`data`](crate::operation::get_job_versions::builders::GetJobVersionsOutputBuilder::data)
    pub fn build(self) -> ::std::result::Result<crate::operation::get_job_versions::GetJobVersionsOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::get_job_versions::GetJobVersionsOutput {
                data: self.data
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("data", "data was not specified but it is required when building GetJobVersionsOutput")
                    )?
                ,
            }
        )
    }
}

