// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListPayloadSpecsInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub org_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub workspace_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub cursor: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub limit: ::std::option::Option<i32>,
}
impl  ListPayloadSpecsInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn org_id(&self) -> ::std::option::Option<&str> {
        self.org_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn workspace_id(&self) -> ::std::option::Option<&str> {
        self.workspace_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cursor(&self) -> ::std::option::Option<&str> {
        self.cursor.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn limit(&self) -> ::std::option::Option<i32> {
        self.limit
    }
}
impl ListPayloadSpecsInput {
    /// Creates a new builder-style object to manufacture [`ListPayloadSpecsInput`](crate::operation::list_payload_specs::ListPayloadSpecsInput).
    pub fn builder() -> crate::operation::list_payload_specs::builders::ListPayloadSpecsInputBuilder {
        crate::operation::list_payload_specs::builders::ListPayloadSpecsInputBuilder::default()
    }
}

/// A builder for [`ListPayloadSpecsInput`](crate::operation::list_payload_specs::ListPayloadSpecsInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListPayloadSpecsInputBuilder {
    pub(crate) org_id: ::std::option::Option<::std::string::String>,
    pub(crate) workspace_id: ::std::option::Option<::std::string::String>,
    pub(crate) cursor: ::std::option::Option<::std::string::String>,
    pub(crate) limit: ::std::option::Option<i32>,
}
impl ListPayloadSpecsInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn org_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.org_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_org_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.org_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_org_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.org_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn workspace_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.workspace_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_workspace_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.workspace_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_workspace_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.workspace_id
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cursor(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.cursor = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cursor(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.cursor = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cursor(&self) -> &::std::option::Option<::std::string::String> {
        &self.cursor
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn limit(mut self, input: i32) -> Self {
        self.limit = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_limit(mut self, input: ::std::option::Option<i32>) -> Self {
        self.limit = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_limit(&self) -> &::std::option::Option<i32> {
        &self.limit
    }
    /// Consumes the builder and constructs a [`ListPayloadSpecsInput`](crate::operation::list_payload_specs::ListPayloadSpecsInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::list_payload_specs::ListPayloadSpecsInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::list_payload_specs::ListPayloadSpecsInput {
                org_id: self.org_id
                ,
                workspace_id: self.workspace_id
                ,
                cursor: self.cursor
                ,
                limit: self.limit
                ,
            }
        )
    }
}

