// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::list_jobs::_list_jobs_input::ListJobsInputBuilder;

pub use crate::operation::list_jobs::_list_jobs_output::ListJobsOutputBuilder;

impl crate::operation::list_jobs::builders::ListJobsInputBuilder {
                    /// Sends a request with this input using the given client.
                    pub async fn send_with(self, client: &crate::Client) -> ::std::result::Result<
                        crate::operation::list_jobs::ListJobsOutput,
                        ::aws_smithy_runtime_api::client::result::SdkError<
                            crate::operation::list_jobs::ListJobsError,
                            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse
                        >
                    > {
                        let mut fluent_builder = client.list_jobs();
                        fluent_builder.inner = self;
                        fluent_builder.send().await
                    }
                }
/// Fluent builder constructing a request to `ListJobs`.
/// 
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct ListJobsFluentBuilder {
                handle: ::std::sync::Arc<crate::client::Handle>,
                inner: crate::operation::list_jobs::builders::ListJobsInputBuilder,
config_override: ::std::option::Option<crate::config::Builder>,
            }
impl
                crate::client::customize::internal::CustomizableSend<
                    crate::operation::list_jobs::ListJobsOutput,
                    crate::operation::list_jobs::ListJobsError,
                > for ListJobsFluentBuilder
            {
                fn send(
                    self,
                    config_override: crate::config::Builder,
                ) -> crate::client::customize::internal::BoxFuture<
                    crate::client::customize::internal::SendResult<
                        crate::operation::list_jobs::ListJobsOutput,
                        crate::operation::list_jobs::ListJobsError,
                    >,
                > {
                    ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
                }
            }
impl ListJobsFluentBuilder {
    /// Creates a new `ListJobsFluentBuilder`.
                    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
                        Self {
                            handle,
                            inner: ::std::default::Default::default(),
    config_override: ::std::option::Option::None,
                        }
                    }
    /// Access the ListJobs as a reference.
                    pub fn as_input(&self) -> &crate::operation::list_jobs::builders::ListJobsInputBuilder {
                        &self.inner
                    }
    /// Sends the request and returns the response.
                    ///
                    /// If an error occurs, an `SdkError` will be returned with additional details that
                    /// can be matched against.
                    ///
                    /// By default, any retryable failures will be retried twice. Retry behavior
                    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
                    /// set when configuring the client.
                    pub async fn send(self) -> ::std::result::Result<crate::operation::list_jobs::ListJobsOutput, ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::list_jobs::ListJobsError, ::aws_smithy_runtime_api::client::orchestrator::HttpResponse>> {
                        let input = self.inner.build().map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
                        let runtime_plugins = crate::operation::list_jobs::ListJobs::operation_runtime_plugins(
                            self.handle.runtime_plugins.clone(),
                            &self.handle.conf,
                            self.config_override,
                        );
                        crate::operation::list_jobs::ListJobs::orchestrate(&runtime_plugins, input).await
                    }
    
                    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
                    pub fn customize(
                        self,
                    ) -> crate::client::customize::CustomizableOperation<crate::operation::list_jobs::ListJobsOutput, crate::operation::list_jobs::ListJobsError, Self> {
                        crate::client::customize::CustomizableOperation::new(self)
                    }
    pub(crate) fn config_override(
                            mut self,
                            config_override: impl ::std::convert::Into<crate::config::Builder>,
                        ) -> Self {
                            self.set_config_override(::std::option::Option::Some(config_override.into()));
                            self
                        }
    
                        pub(crate) fn set_config_override(
                            &mut self,
                            config_override: ::std::option::Option<crate::config::Builder>,
                        ) -> &mut Self {
                            self.config_override = config_override;
                            self
                        }
    #[allow(missing_docs)] // documentation missing in model
    pub fn org_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.org_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_org_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_org_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_org_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_org_id()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn workspace_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.workspace_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_workspace_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_workspace_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_workspace_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_workspace_id()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn cursor(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.cursor(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_cursor(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_cursor(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_cursor(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_cursor()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn limit(mut self, input: i32) -> Self {
                    self.inner = self.inner.limit(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_limit(mut self, input: ::std::option::Option<i32>) -> Self {
                    self.inner = self.inner.set_limit(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_limit(&self) -> &::std::option::Option<i32> {
                    self.inner.get_limit()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn endpoint(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.endpoint(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_endpoint(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_endpoint(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_endpoint(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_endpoint()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn trigger_type(mut self, input: crate::types::TriggerTypeEnum) -> Self {
                    self.inner = self.inner.trigger_type(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_trigger_type(mut self, input: ::std::option::Option<crate::types::TriggerTypeEnum>) -> Self {
                    self.inner = self.inner.set_trigger_type(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_trigger_type(&self) -> &::std::option::Option<crate::types::TriggerTypeEnum> {
                    self.inner.get_trigger_type()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(mut self, input: crate::types::JobStatusEnum) -> Self {
                    self.inner = self.inner.status(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::JobStatusEnum>) -> Self {
                    self.inner = self.inner.set_status(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_status(&self) -> &::std::option::Option<crate::types::JobStatusEnum> {
                    self.inner.get_status()
                }
}

